---
title: "ECN 6578A, Économétrie des marchés financiers, Hiver 2020"
subtitle: "Cours 10"
author: "William McCausland"
date: "`r Sys.Date()`"
output: beamer_presentation
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

## Obligations

* Un obligation est un contrat entre un *émetter* (pays, province, état, municipalité, entreprise) et un *détenteur*.
* Le détenteur peut vendre l'obligation dans un marché.
* L’émetteur verse un paiement, la *valeur nominale* (face value) au détenteur à l'*échance*.
* Habituellement l'émetteur verse des *coupons* réguliers au détenteur jusqu'à l'échéance (inclusif).
* Pour les obligations *zéro coupon* il n'y a pas de coupon.
* $P_{nt}$ est le prix à $t$ d'une obligation zéro coupon qui paie un dollar dans $n$ périodes et $p_{nt} \equiv \log(P_{nt})$.

## Rendements des obligations

* Le rendement à l'échéance (yield) $Y_{nt}$ de cette obligation vérifie
$$ P_{nt} = \frac{1}{(1+Y_{nt})^n}. $$
* Le log-rendement $y_{nt} = \log (1+Y_{nt})$ vérifie
$$ y_{nt} = -\frac{p_{nt}}{n}. $$

## Rendements "Holding Period"

* On peut calculer un *rendement pendant la période de détention* (holding period return) pour une obligation :
$$ (1+R_{n,t+1}) = \frac{P_{n-1,t+1}}{P_{nt}} = \frac{(1+Y_{nt})^n}{(1+Y_{n-1,t+1})^{n-1}}. $$
* En logarithmes,
$$ r_{n,t+1} = p_{n-1,t+1} - p_{nt} = y_{nt} - (n-1)(y_{n-1,t+1} - y_{nt}). $$
* Le rendement à l'échéance (connu à $t$) est la moyenne de rendements à venir :
$$ y_{nt} = -p_{nt}/n = \frac{1}{n} \sum_{i=0}^{n-1} r_{n-i,t+1+i}. $$
* Attention : si les taux d'intérêt montent, le prix des obligations tombe.

## La structure à terme

* La *structure à terme* est l'ensemble de rendements à l'échéance pour des obligations zéro coupon de maturité différentes.
* La courbe de rendement (yield curve) est la graphique de $Y_{nt}$ ou $y_{nt}$ contre $n$.
* L'écart de rendement (yield spread) à $t$ est $S_{nt} \equiv Y_{nt} - Y_{1t}$ ou $s_{nt} \equiv y_{nt}-y_{1t}$.

## Cours à terme (forward rates)

* Voici une façon de garantir à $t$ un taux d'intérêt entre $t+n$ et $t+n+1$ (le taux étant déterminé par les prix marchands).
    * acheter une obligation qui paie un dollar à $t+n+1$
    * vendre assez de l'obligation qui paie un dollar à $t+n$ pour financer cet achat. (c.-à-d. vendre une quantité $P_{n+1,t}/P_{nt})$ de cette obligation)
* Le *cours à terme* (forward rate) est le taux garanti :
$$ 1 + F_{nt} = \frac{P_{nt}}{P_{n+1,t}}. $$

## Modèles de la structure à terme

*  Rappel : $P_{nt}$ le prix à $t$ d'une obligation zéro coupon, qui paie 1 dollar à $t+n$.
*  $P_{nt} = E_t[P_{n-1,t+1} M_{t+1}]$ où $M_{t+1}$ est le
    facteur d'actualisation stochastique.
*  L'itération donne $P_{nt}=E_t[M_{t+1}M_{t+2}\cdots M_{t+n}]$.
*  La log-normalité conjointe conditionnelle des
    $P_{1t}, P_{2t}, \ldots$ et $M_{t+1}$ donne l'équation
    de valorisation :
    \[ p_{nt} = E_t[m_{t+1} + p_{n-1,t+1}] +
    \frac{1}{2} \mathrm{var}_t[m_{t+1} + p_{n-1,t+1}], \]
    où
    \[ p_{nt} = \log(P_{nt}), \quad m_{t+1} = \log(M_{t+1}). \]

## Modèle de Vasicek (1977)

*  Dans ce modèle, $m_{t+1}$ est homoscédastique.
*  On peut toujours écrire
    \[ -m_{t+1} = x_t + \epsilon_{t+1}, \]
    où $E_t[-m_{t+1}] = x_t$ et $E_t[\epsilon_{t+1}] = 0$.
*  Selon le modèle, le facteur $x_t$ est AR(1) :
    \[ x_{t+1} = (1-\phi) \mu + \phi x_t + \xi_{t+1}. \]
*  En général, $\epsilon_{t+1}$ et $\xi_{t+1}$ sont corrélés : $\epsilon_{t+1} = \beta \xi_{t+1} + \eta_{t+1}$.
*  La partie de $\epsilon_{t+1}$ non-corrélée avec $\xi_{t+1}$ n'est pas
    importante et on l'élimine, alors
    \[ -m_{t+1} = x_t + \beta \xi_{t+1}. \]
*  On a un seul choc dans le système : $\xi_t$. Soit $\sigma^2$
    sa variance.

## Valorisation des obligations I : Le taux court

*  Le log-prix d'une obligation à une période vérifie
    (parce que $p_{0,t+1} = \log P_{0,t+1} = \log 1 = 0$)
    \[ p_{1t} = E_t[m_{t+1}] + \frac{1}{2} \mathrm{var}_t[m_{t+1}]. \]
*  Dans le modèle de Vasicek,
    \[ p_{1t} = -x_t + \beta^2 \sigma^2/2. \]
*  Rappelez que le rendement à l'échéance et
    \[ y_{1t} = -p_{1t} = x_t - \beta^2 \sigma^2/2. \]
*  Remarquez que $y_{1t}$ est affine en $x_t$.

## Valorisation des obligations II : d'autres échéances

*  On devine (et vérifie plus tard) que dans le modèle de Vasicek,
    $p_{nt}$ (et alors $y_{nt} = -p_{nt}/n$) est aussi affine en $x_t$ :
    \[ -p_{nt} = A_n + B_n x_t \]
*  On sait déjà que $A_0 = B_0 = 0$, $A_1 = -\beta^2 \sigma^2/2$
    et $B_1 = 1$.
*  On vérifie que l'équation de prix affine est correcte et
    on obtient les coefficients avec
    \[ E_t[m_{t+1} + p_{n-1,t+1}] =
    -x_t - A_{n-1} - B_{n-1}(1-\phi)\mu - B_{n-1} \phi x_t \]
    \[ \mathrm{var}_t[m_{t+1} + p_{n-1,t+1}] = (\beta+B_{n-1})^2 \sigma^2 \]
*  Après substitution dans l'équation de valorisation, on obtient
    \[ A_n + B_n x_t - x_t - A_{n-1} - B_{n-1}(1-\phi)\mu - B_{n-1}\phi x_t
    + (\beta + B_{n-1})^2 \sigma^2/2 = 0 \]

## D'autres échéances, continu

*  Cette équation doit tenir pour chaque $x_t$, alors le coefficient
    de $x_t$ et le coefficient constant doivent égaler à zéro.
*  Alors
    \[ B_n = 1 + \phi B_{n-1} = (1-\phi^n)/(1-\phi) \]
    \[ A_n = A_{n-1} + (1-\phi) \mu B_{n-1} - (\beta + B_{n-1})^2\sigma^2/2 \]
*  Une version discrète du modèle célèbre Cox, Ingersoll Ross
    (1985) est
    \[ -m_{t+1} = x_t + x_t^{1/2} \epsilon_{t+1} \]
    \[ x_{t+1} = (1-\phi)\mu + \phi x_t + x_t^{1/2} \xi_{t+1} \]
*  C'est aussi un modèle affine avec un facteur.
*  Il y a aussi des modèles avec plusieurs facteurs et des modèles
    qui ne sont pas affines.

## Types de marchés financiers I

1. Marchés gouvernés par les ordres (order driven) (TSX)
    * ordre à cours limité (limit order)
        * ordre d'achat ou ordre de vente
        * proposition de prix
        * durée spécifiée
        * possibilité d'échéance
    * ordre au marché (market order)
        * ordre d'achat ou ordre de vente
        * au meilleur prix proposé de l'autre coté du marché
        * immédiate
    * variations
    
## Types de marchés financiers II

2. Marchés gouvernés par les prix (quote driven) (NYSE, NASDAQ)
    * Teneur du marché (market maker) (un ou plusieurs concurrents)
    * Cours acheteur (bid price) < cours vendeur (ask price)
    * Raisons pour la fourchette acheteur/vendeur :
        * coûts d'affaires ordinaires
        * coûts d'inventaires (risque)
        * information asymétrique

## Données de haute fréquence

* Information pour chaque transaction :
    * Prix, quantité, identité de l'actif
    * Date et heure (souvent en secondes, $ms$)
    * Achat ou vente (du point de vue du client du teneur du marché)
    * Achat ou vente (par rapport de l'émetteur de l'ordre au marché)
    * Échange d'un initié ou non

* Sources du « bruit »
    * Quantification du prix (1/8) \$ puis (1/16) \$ puis 0.01 \$
    * Quantification du temps (secondes, puis $ms$)
    * Différence entre le cours acheteur et le cours vendeur
    * La valeur peut changer sans qu'une transaction le rend observé (le prix est rassis)
    * Erreurs (des échangeurs, teneurs des registres)

* Aspect asynchrone

## Pourquoi étudier les données de haute fréquence

L'importance:

1. Plus de détail sur la dynamique des prix
1. Information sur la liquidité des marchés, le processus de la découverte des prix (price discovery).
1. Mesures de volatilité
1. Comprendre la microstructure des marchés

La prudence est nécessaire : le bruit de microstructure

## Covariances trompeuses (spurious covariances)

* Rendements latents :
$$ \begin{bmatrix} R_{At} \\ R_{Bt} \end{bmatrix} \sim \mathrm{iid}\,
N\left(
\begin{bmatrix} \mu_A \\ \mu_B \end{bmatrix},
\begin{bmatrix} \Sigma_{AA} & \Sigma_{AB} \\ \Sigma_{AB} & \Sigma_{BB} \end{bmatrix}
\right) $$

* Processus d'observation : $z = \{z_{it}\}_{i\in \{A,B\},\, t\in {\mathrm{N}}}$
    * pour $i=A,B$, $z_{it} = 1$ si l'actif $i$ est échangé à $t$, $z_{it} = 0$ sinon.
    * les $z_{it}$ sont mutuellement indépendants
    * $z_{it} = 0$ (pas de transaction) avec probabilité $\pi_i$, $i=A,B$
    
* Rendements observés :
$$ r_{At}^\circ = \begin{cases}
0 & z_{At} = 0 \\
r_{At} & z_{At} = 1,\, z_{A,t-1} = 1 \\
r_{At} + r_{A,t-1} & z_{At} = 1,\, z_{A,t-1} = 0,\, z_{A,t-2} = 1 \\
r_{At} + r_{A,t-1} + r_{A,t-2} & z_{At} = 1,\, z_{A,t-1} = z_{A,t-2} = 0,\, z_{A,t-3} = 1 \\
\vdots \\ \end{cases} $$

## La moyenne et la variance de $r_{At}^\circ$

* Séries géométrique, $|x|<1$ :
$$ \sum_{\tau=0}^\infty x^\tau = \frac{1}{1-x} $$
* Sa dérivée par rapport à $x$ :
$$ \sum_{\tau=0}^\infty \tau x^{\tau-1} = \sum_{\tau=1}^\infty \tau x^{\tau-1} = \frac{1}{(1-x)^2}. $$
* Maintenant,
$$ E[r_{At}^\circ] = E[E[r_{At}^\circ|z]] = \sum_{\tau=1}^\infty (1-\pi_A)^2 \pi_A^{\tau-1} \tau \mu_A = \mu_A, $$
$$ \begin{aligned} E[(r_{At}^\circ)^2] = E[E[(r_{At}^\circ)^2|z]] &= \sum_{\tau=1}^\infty (1-\pi_A)^2 \pi_A^{\tau-1} [(\tau \mu_A)^2 + \tau \Sigma_{AA}] \\ &= \Sigma_{AA} + \frac{1+\pi_A}{1-\pi_A} \mu^2_A. \end{aligned} $$
$$ \mathrm{Var}[r_{At}^\circ] = \Sigma_{AA} + \frac{2\pi_A}{1-\pi_A}\mu_A^2. $$

## Application de la loi de covariance totale

* Selon le modèle,
$$ \mathrm{Cov}[r_{At},r_{A,t-k}] = \begin{cases} \Sigma_{AA} & k=0 \\ 0 & k\neq 0 \end{cases}, $$
$$ \mathrm{Cov}[r_{At},r_{B,t-k}] = \begin{cases} \Sigma_{AB} & k=0 \\ 0 & k\neq 0 \end{cases}. $$

* Question: $\mathrm{Cov}[r_{At}^\circ,r_{A,t-k}^\circ] = 0$ et $\mathrm{Cov}[r_{At}^\circ,r_{B,t-k}^\circ] = 0$ pour $k>0$?

* La loi de covariance totale en général,
$$ \mathrm{Cov}[X,Y] = E[\mathrm{Cov}[X,Y|Z]] + \mathrm{Cov}[E[X|Z], E[Y|Z]]. $$

## Autocovariances

* Cas spécial, auto-covariances : $X = r_{At}^\circ$, $Y = r_{A,t-k}^\circ$, $Z = z$ :
$$ \mathrm{Cov}[r_{At}^\circ,r_{A,t-k}^\circ] = E[\mathrm{Cov}[r_{At}^\circ,r_{A,t-k}^\circ|z]] + \mathrm{Cov}[E[r_{At}^\circ|z], E[r_{A,t-k}^\circ|z]]. $$

* Sachant $z$, les sommes $r_{At}$ et $r_{A,t-k}$ ne se chevauchent pas et
$$ \mathrm{Cov}[r_{At}^\circ,r_{A,t-k}^\circ|z] = 0. $$

* Calcul de $\mathrm{Cov}[E[r_{At}^\circ|z], E[r_{A,t-k}^\circ|z]]$ : exercice.

* Résultat : $\mathrm{Cov}[E[r_{At}^\circ|z], E[r_{A,t-k}^\circ|z]] = -\pi_A^k \mu_A^2$.

## Covariances croisées

* Cas spécial : $X = r_{At}^\circ$, $Y = r_{B,t-k}^\circ$, $Z = z$ :
$$ \mathrm{Cov}[r_{At}^\circ,r_{B,t-k}^\circ] = E[\mathrm{Cov}[r_{At}^\circ,r_{B,t-k}^\circ|z]] + \mathrm{Cov}[E[r_{At}^\circ|z], E[r_{B,t-k}^\circ|z]]. $$

* Puisque $z_A$ et $z_B$ sont indépendants,
$$ \mathrm{Cov}[E[r_{At}^\circ|z], E[r_{B,t-k}^\circ|z]] = 0. $$

* Puisque $r_{At}^\circ$ comprend $r_{A,t-k-\tau}$ et $r_{B,t-k}$ comprend $r_{B,t-k-\tau}$ avec probabilité conjointe $(1-\pi_A)(1-\pi_B)\pi_A^k (\pi_A\pi_B)^\tau$,
$$ \begin{aligned} E[\mathrm{Cov}[r_{At}^\circ,r_{B,t-k}^\circ|z]]
&= (1-\pi_A)(1-\pi_B)\pi_A^k \sum_{\tau=0}^\infty (\pi_A \pi_B)^\tau \Sigma_{AB} \\ &= \frac{(1-\pi_A)(1-\pi_B)}{1-\pi_A\pi_B} \pi_A^k \Sigma_{AB} \end{aligned}. $$

## Rebond acheteur/vendeur I

* Modèle simple illustratif, version 1 :
    * Transactions aux prix $P_t \in \{P_a, P_v\}$, $t=0,1,2,\ldots$
    * $P_v-P_a \equiv S > 0$.
    * $P_t$ est iid.
    * $P_t = P_v$ avec probabilité 0.5, $P_t = P_a$ avec probabilité 0.5
    * $\Delta P_t \equiv P_t - P_{t-1}$.
* Calcul des moments
    * $E[\Delta P_t] = 0$ par stationnarité
    * $\mathrm{Var}[\Delta P_t] = \frac{1}{4} S^2 + \frac{1}{4} (-S)^2 + \frac{1}{4} 0 + \frac{1}{4} 0 = \frac{S^2}{2}$
    * $\mathrm{Cov}[\Delta P_t, \Delta P_{t-1}]
    = \frac{1}{8} S(-S) + \frac{1}{8} (-S)S + \frac{2}{8} 0\cdot 0 + \frac{1}{8} 0\cdot S + \frac{1}{8} S \cdot 0 + \frac{1}{8} 0\cdot (-S) + \frac{1}{8} (-S)\cdot 0 = -\frac{S^2}{4}$
    * $\mathrm{Corr}[\Delta P_t, \Delta P_{t-1}] = -0.5$
    * $\mathrm{Cov}[\Delta P_t, \Delta P_{t-k}] = 0$ pour $k > 1$ parce que $(P_t,P_{t-1})$ et $(P_{t-k},P_{t-k-1})$ sont indépendantes.

## Rebond acheteur/vendeur II

* Modèle avec changements de valeur :
    * $P_t = P_t^* \pm S/2$
    * $\Delta P_t^* = P_t^* - P_{t-1}^* \sim \mathrm{iid} (0,\sigma^2)$
    * La séquence $P_t^*$ et les réalisations $\pm S/2$ sont indépendantes.
    * $\mathrm{Var}[\Delta P_t] = \sigma^2 + S^2/2$
    * $\mathrm{Cov}[\Delta P_t, \Delta P_{t-1}] = -S^2/4$, inchangé
    * réduction de corrélation.
