---
title: "Lectures et exercices théoriques"
author: "William McCausland"
date: "`r Sys.Date()`"
output: pdf_document
urlcolor: blue
---

## Avant l'intra

### Cours 1

#### Lectures

1. Tsay, 3e édition :
    a. 1.1 rendements

#### Exercices

1. Pour les deux placements décrits à la diapo "Fonctions linéaires vs mélanges, un exemple", calculez la moyenne et la variance du rendement.

1. Étudiez la preuve du théorème de variance totale et prouvez le théorème de covariance totale : pour variables aléatoires $X$, $Y$ et $Z$ telles que les moments suivants existent,
\[
  \mathrm{Cov}[X,Y] = E[\mathrm{Cov}[X,Y|Z]] + \mathrm{Cov}[E[X|Z], E[Y|Z]].
\]

1. Trouvez $\mathrm{Var}[\mu]$ dans l'Application II de la loi des espérances itérées.
Il y a deux façons. Vous pouvez confirmer que les deux façons donnent le même résultat.
Les deux façons :
    a. Trouvez $\mathrm{Var}[\mu]$ directement comme $E[\mu^2] - E[\mu]^2$
    a. Trouvez $\mathrm{Var}[\mu]$ indirectement avec les expressions de $E[R]$, $E[R^2]$ et $\mathrm{Var}[R]$ sous "Calcul de quelques moments".

### Cours 2

#### Lectures avant le cours

1. Tsay, 3e édition :
    a. 1.2.2 la loi des rendements
    a. 1.2.3 rendements multivariés
    a. 1.2.5 propriétés empiriques des rendements
    a. 2.1 stationnarité
    a. 2.2 corrélation et la fonction d'autocorrélation
    a. 2.3 le bruit blanc et les séries temporelles linéaires

#### Autres lectures

1. L'article de Cont (2001) que j'ai mis sur StudiUM.
1. Tsay, 3e édition :
    a. 1.2.1 lois statistiques et leurs moments

#### Exercices

1. La v.a. $X$ suit une loi qui est un mélange de deux lois gaussiennes, chacune avec probabilité 0.5 : $N(\mu,\sigma^2)$ et $N(-\mu,\sigma^2)$.
Calculez l'aplatissement $K_x$ et $\lim_{\sigma^2 \downarrow 0} K_x$.

1. Trouvez l'asymétrie et l'aplatissement d'un mélange général de deux v.a. gaussiennes.
Le site suivant donne les quatres premiers moments non centraux d'une v.a. $N(\mu,\sigma^2)$ : <https://fr.wikipedia.org/wiki/Loi_normale#Moments>.

1. Le prix d'un actif le 4 janvier est de 14.50 dollars. Le prix de l'actif le 15 fevrier est de 13.15. Quel est le rendement simple annualisé et le log rendement annualisé?

1. On observe un échantillon $X_1,\ldots,X_T$, où $X_t \sim \mathrm{iid}\, N(\mu,\sigma^2)$.
Si on fait les tests 1 et 2 de la diapo "Attention : tests multiples!" quelle est la probabilité d'au moins un rejet, comme fonction de $\alpha$?

### Cours 3

#### Lectures avant le cours

1. Tsay, 3e édition :
    a. 2.4 Intro (avant 2.4.1)
    a. 2.5 Intro (avant 2.5.1)
    a. 2.6 Intro (avant 2.6.1)

#### Autres lectures

1. Tsay, 3e édition :
    a. 2.4 (modèles AR)
    a. 2.5 (modèles MA)
    a. 2.6 (modèles ARMA)
    a. 2.8.1 et 2.8.2 (pour faire l'exercise 2.4)

#### Exercices

1. Ecrivez les équations Yule-Walker pour un process AR(3) et pour un processus ARMA(1,1).

1. Trouvez la fonction d'autocorrélation pour un processus MA(3).

1. Considérez le process AR(3) suivant :
\[
  r_t = 1.9 r_{t-1} - 1.4 r_{t-2} + 0.45 r_{t-3} + a_t.
\]
    a. Trouvez les racines du polynome caracteristique du processus.
    a. Est-ce que la condition de stationnarité tient?

1. Trouvez $\psi_1,\psi_2,\psi_3$ de la représentation MA infinie pour un ARMA(1,2) général.

### Cours 4

#### Lectures avant le cours

1. Tsay, 3e édition :
    a. Chapitre 3 jusqu'à l'introduction de 3.4 (avant 3.4.1) 

#### Autres lectures

1. Tsay 3e édition :
    a. Sections 1.2.2 (Distributions des rendements)
    a. Sections 1.2.4 (Fonction de vraisemblance des rendements)
    a. Section 3.4.1 (Propriétés des modèles ARCH)
    a. Section 3.4.2 (Faiblesses des modèles ARCH)

#### Exercices

1. Mettons que $r_t$ suit un modèle ARMA(1,3) avec moyenne zéro.
Au moment $t$, trouvez les prévisions de $r_{t+1}$ et de $r_{t+2}$ qui minimisent l'erreur moyenne carrée.
Trouvez la variance de l'erreur de prévision dans les deux cas.

1. Mettons que $r_t$ suit un GARCH(1,1) gaussien avec moyenne zéro.
Calculez la variance, l'asymétrie et l’aplatissement de $r_t$. Vous pouvez vérifier la variance et l'aplatissement en comparant vos résultats aux résultats à la page 132 de Tsay.

### Cours 5

#### Lectures avant le cours

1. Dans Tsay, 3e édition :
    a. 3.5 intro (avant 3.5.1) (Modèle GARCH)
    a. 3.8 intro, 3.8.1 (Modèle EGARCH)
    
1. Au site web suivant : https://fr.wikipedia.org/wiki/Maximum_de_vraisemblance
    a. Sections Exemple, Principe, Définitions, Propriétés, Exemples

#### Autres lectures

1. Dans Tsay, 3e édition :
    a. 3.5.1 (exemple GARCH)

#### Exercices

1. Trouvez la moyenne et la variance de $\ln \sigma^2_t$ pour un modèle EGARCH(1,1)

1. Faites des prévision du rendement $r_{T+1}$ pour une modèle AR(1)-GARCH(1,1).
Quelle est la variance conditionnelle des erreurs de prévision? Exprime le résultat en termes des paramètres, de $r_T$ et de $\sigma_T^2$.

### Cours 6

#### Lectures avant le cours

1. Dans Tsay, 3e édition :
    a. 3.12 (Modèle de volatilité stochastique)
    a. 12.3 intro, 12.3.1 (inférence bayésienne, lois postérieures)

#### Autres lectures

#### Exercices

1. Trouvez la loi *a posteriori* quand les observations sont iid $\mathrm{Poisson}(\lambda)$ et la loi *a priori* de $\lambda$ est la loi $\mathrm{Gamma(\bar\alpha, \bar\beta)}$, où $\bar\alpha$ et $\bar\beta$ sont des hyperparamètres fixes.

1. Trouvez la loi *a posteriori* conditionnelle de $h$ dans le modèle gaussien.

1. Prenez le modèle de volatilité stochastique. L'exercice est de trouver comment construire la densité prédictive $f(y_{T+1}|y_1,\ldots,y_T)$ sur une grille de points.
    a. Montrez que
\[
  f(y_{T+1}|y_1,\ldots,y_T) = E[f(\log h_{T+1}|\log h_T, \theta, y_1,\ldots,y_T)
  \cdot
  f(y_{T+1}|\log h_{T+1}, \log h_T, \theta, y_1,\ldots,y_T)],
\]
où l'espérance est par rapport à la loi conditionnelle de $(\theta,h_T)$ sachant $y_1,\ldots,y_T$.
    a. Écrivez les densités $f(\log h_{T+1}|\log h_T, \theta, y_1,\ldots,y_T)$ et $f(y_{T+1}|\log h_{T+1}, \log h_T, \theta, y_1,\ldots,y_T)$ en utilisant les équations d'état et d'observation.
    a. Comment peut-on approximer la densité prédictive $f(y_{T+1}|y_1,\ldots,y_T)$ sur une grille à partir d'un échantillon de la loi de $\theta,\log h_T|y_1,\ldots,y_T$? Indice: comme étape intermédiaire, créez un échantillon de la loi de $\theta,\log h_T,\log h_{T+1}|y_1,\ldots,y_T$.
    
## Après l'intra

### Cours 7

#### Lectures

1. CLM 5.0, 5.1, 5.2, 5.3
1. CLM 5.7.1 (anomalies)
1. CLM 6.0, 6.1 (APT)

#### Exercices

1. Prouvez les 5 résultats des diapos 16 et 17, « Résultats I » et « Résultats II »

Voici des suggestions pour les 5 résultats :

1. Le résultat dépend de l'unicité de la solution $g + \mu_p h$.
Si vous n'en servez pas, la solution est incorrecte.
1. Exprimez $\sigma_p^2 \equiv (g + \mu_ph) \Omega (g + \mu_ph)$ et minimisez. Écrivez le résultat en terms de $\mu$, $\Omega$.
1. La covariance entre le rendement du portefeuille
$g + \mu_p h$ et celui du portefeuille $g + \mu_q h$ est
$(g+\mu_ph)\Omega(g+\mu_qh)$.
1. Servez-vous du troisième résultat pour trouver le $\mu_{op}$ unique, en termes de $\mu_p$, qui donne $\mathrm{Cov}[R_p,R_{op}] = 0$.
1. La covariance entre le rendement du portefeuille $p$ sur le FMV et le portefeuille arbitraire $\omega$ est
$(g+\mu_ph)\Omega\omega$.
Écrivez-la en forme $\lambda \mu_i + \gamma$, où $\mu_i = E[R_i]$, et $\lambda$ et $\gamma$ sont des fonctions de $\mu_p, A, B, C, D$.
Écrivez l'équation pour deux cas spéciaux, $i=op$ et $i=p$, pour obtenir (5.2.19) dans le manuel CLM.

### Cours 8, 9

#### Lectures avant le premier cours

1. CLM 8 intro, 8.1 avant 8.1.1

#### Autres lectures

1. CLM 8.1 (FAS)
1. CLM 8.2 (CCAPM, utilité isoélastiques, casse-têtes empiriques)
1. CLM 8.4 Utilité Epstein-Zin, utilité non-séparable
1. CLM A.2 GMM

#### Exercices

1. Considérez le milieu introduit à la diapo "Absence d'arbitrage et le FAS". Il y a $S=2$ états et 2 actifs. Le premier actif a un rendement net $R_f$ dans les deux états et coûte 100 $. Le deuxième actif a un rendement net $R_1$ dans le permier état et un rendement net $R_2$ dans le deuxième et coûte 500 $.
    a. Donnez les matrices $X$ et $G$ et le vecteur $q$ en termes de $R_f$, $R_1$ et $R_2$.
    a. Donnez une condition nécessaire et suffisante sur $R_f$, $R_1$ et $R_2$ pour la complétion du marché.
    a. Supposant que le marché est complet, trouvez le vecteur des prix d'états et donnez une condition supplémentaire sur $R_f$, $R_1$ et $R_2$ pour l’absence d'arbitrage.
    a. Si les états sont équiprobable ($\pi_1 = \pi_2 = 0.5$) trouvez le facteur d'actualisation stochastique.

2. Considérez le problème à la diapo "Un problème à deux périodes sans incertitude".
    a. Démontrez que si $(C_t^{(i)}, C_{t+1}^{(i)})$ est une solution du problème pour un consommateur avec revenu $m_i$, $i=1,2$, que $(C_t^{(1)}+C_t^{(2)}, C_{t+1}^{(1)}+C_{t+1}^{(2)})$ est une solution du problème pour un consommateur avec revenu $m_1 + m_2$. 
    a. Généralisez le problème à trois périodes. Le taux d'intérêt $R$ est constant et la pondération de $U(C_{t+2})$ est $\delta^2$. Démontrez que pour la solution $(C_t, C_{t+1}, C_{t+2})$, les ratios $C_{t+2}/C_t$ et $C_{t+1}/C_t$ ne dépendent pas du revenu $m$.

#### Questions (Cours 9)

1. Regardez l'expression pour $r_{f,t+1}$ dans le modèle CCAPM avec préférences Epstein-Zin. Pourquoi est-ce la moyenne historique de $r_{f,t+1}$ est plus cohérente avec ce modèle, par rapport au modèle avec préférences isoélastique, quand $\gamma$ est très élevé?
1. Regardez l'expression pour la prime de risque associée à l'actif $i$ dans le même modèle. Quelle est la prime de risque associée au marché (ou portefeuille agrégé)? Pourquoi est-ce que les préférences E-Z aident à capturer la prime historique des actions, par rapport aux préférences isoélastique?
1. Supposons qu'on utilise la méthode GMM pour estimer les paramètres $\delta$ et $\gamma$ du modèle CCAPM avec utilité isoélastique.
On observe $w_t = (C_t, C_{t+1}, R_{t+1}, Z_t)$, $t=1,\ldots,T$.
    a. Pourquoi est-ce qu'on ne devrait pas utiliser, comme élément de $Z_t$, une variable qui n'est pas observée à $t+1$?
    a. Mettons que $Z_t$ comprend une variable observée à $t$ mais qui n'aide pas à prévoir la consommation future $C_{t+1}$. Quelles sont les implications pour l'inférence GMM?
1. Si la fonction de moment $g(w_t,\theta)$ (un vecteur) a un élément qui est une fonction de $w_t$ mais pas de $\theta$, quelles sont les implications pour l'estimation est les tests.

### Cours 10

#### Lectures

* CLM 10.1, 11.1 (Obligations)
* CLM 3.1, 3.2 (Données de haute fréquence)
* Tsay 5.1, 5.2 (Données de haute fréquence)

#### Exercices

1. Dérivez les équations (11.1.21) et (11.1.23) dans CLM.

1. Terminez la preuve de
$$ \mathrm{Cov}[r_{At}^\circ,r_{A,t-k}^\circ] = -\pi_A^k \mu_A^2. $$

1. Dans le modèle de rebond acheteur/vendeur, supposez qu'un achat (au cours vendeur) est plus probable quand le prix latent augmente.
Plus spécifiquement, supposez qu'avec probabilité $1/2$, $P_t^* \sim (P_{t-1}^* + \mu, \sigma^2)$ et $P_t = P_t^* + S/2$ et qu'avec probabilité $1/2$, $P_t^* \sim (P_{t-1}^* - \mu, \sigma^2)$ et $P_t = P_t^* - S/2$.
Trouvez $E[\Delta P_t]$, puis $\mathrm{Cov}[\Delta P_t,\Delta P_{t-1}]$.

### Cours 11

#### Lectures

* Tsay 5.4.1, 5.5, Appendix B du chapitre 5.

### Cours 12

#### Lectures

* Tsay 7 (intro), 7.1, 7.2, 7.3, 7.4



