---
title: "Exercices R"
author: "William McCausland"
date: "`r Sys.Date()`"
output: pdf_document
---

### Premier travail pratique

1. Travail préliminaire (le 6 janvier, pas à remettre)
    a. Téléchargez R et R Studio.
    a. Créez un fichier HTML à partir du gabarit R Markdown.

1. Travail, cours du 13 janvier
    a. Téléchargez le fichier des données `d-3m7008.txt` et faites la graphique des rendements journaliers de l'action 3M avec la commande `plot`.
    a. Faites un test de l'hypothèse que les rendements sont iid gaussiens, avec la statistique test Jarque-Bera. Calculez les valeurs critiques en utilisant la fonction de quantile (comme `qnorm` ou `qchisq`) de la loi asymptotique de la statistique test sous l'hypothèse nulle.
    a. Faites un test de l'hypothèse que les rendements sont iid avec variance finie, avec la statistique test Box-Pierce. Utilisez la commande `acf` pour obtenir la fonction d'autocorrélation et calculez la statistique test à partir de cette fonction. Utilisez $m=10$ retards. Confirmez ensuite votre réponse en utilisant la commande `Box.test`.

1. Travail, cours du 20 janvier
    a. Considérez le process ARMA(3,1) suivant :
\[
  r_t = 1.9 r_{t-1} - 1.4 r_{t-2} + 0.45 r_{t-3} + a_t - 0.3 a_{t-1}.
\]
        i. Simulez le séries pour $T=500$ observations.
        i. Faites la graphique de la fonction d'autocorrélation $\rho_k$ de la population, pour $k=1,\ldots,25$
        i. Faites la graphique de la fonction d'autocorrélation $\hat\rho_k$ de l'échantillon, pour $k=1,\ldots,25$.
        i. Estimez les paramètres d'un modèle ARMA(3,1) en vous servant de l'échantillon que vous avez tiré. Donnez des estimations ponctuelles avec leurs écarts-types.
    a. Tsay, Exercice 2.4. Lisez les sections 2.8.1 et 2.8.2 sur la saisonnalité.

1. Travail, cours du 27 janvier
    a. Prenez le code de la diapo 'Simulation du modèle ARCH(3)' et modifiez-le pour simuler un GARCH(1,1) gaussien à moyenne zéro pendant $T=1000$ périodes.
Utilisez les valeurs des paramètres $\alpha_0 = 0.000084$, $\alpha_1 = 0.1213$, $\beta_1 = 0.8523$.
    a. Calculez la variance, l'asymétrie et l'aplatissement de l'échantillon.
Suggestion : comparez à la variance, à l'asymétrie et l’aplatissement de la population obtenues dans les exercices théoriques.
    a. Faites la graphique de $r_t$ et de $\sigma_t^2$. 

1. Travail, cours du 3 février
    a. Pour cette question, utilisez les données dans le fichier d-3m7008.txt (action 3M, rendements journaliers, 1970-2008).
Je recommande le paquet fGARCH.
Pour tous les modèles suivants, calculez la valeur maximale de la log-vraisemblance.
Quel est le meilleur modèle selon le critère AIC?
Pour ce modèle, reportez les estimations MV (maximum de vraisemblance) des paramètres et leurs écarts-types asymptotiques et faites la graphique de la séquence de volatilités estimées.
        i. GARCH(1,1), distribution conditionnelle gaussienne.
        i. GARCH(1,1), distribution conditionnelle $t$ de Student.
        i. ARCH(2), distribution conditionnelle $t$ de Student.
        i. GARCH(2,1), distribution conditionnelle $t$ de Student.
        i. AR(1)-GARCH(1,1), distribution conditionnelle $t$ de Student.

### Deuxième travail pratique

1. Travail, cours du 23 février.
Les rendements mensuelles de $N=4$ actifs pendant 1962-1999 se trouvent dans les fichiers `m-ibm6299` (IBM), `m-gm6299` (GM), `m-hsy6299` (Hershey Foods) et `m-aa6299` (Alcoa). Les commandes R `cbind` (empilation horizontale des vecteurs) `%*%` (multiplication matricielle) et `scan` (chargement des données) seront utiles.

    a. Trouvez les estimations maximum de vraisemblance $\hat{\mu}$ et $\hat{\Sigma}$ pour le modèle où le vecteur des rendements réels des $N$ actions est iid $N(\mu,\Sigma)$. (Comme dans le cas univarié, l'estimateur MV de la moyenne de la population, $\mu$, est la moyenne de l'échantillon et l'estimateur MV de la variance de la population, $\Sigma$, est la variance de l'échantillon, avec le nombre de périodes $T$ au dénominateur).
    a. Trouvez la courbe de la frontière minimum variance des portefeuilles construits à partir des $N$ actions. Utilisez $\hat{\mu}$ et $\hat{\Sigma}$ de la première question pour la moyenne et la variance.
    a. Sur le même graphique, mettez les points qui représente la moyenne et l'écart type du rendement de chaque action.
    
1. Travail, cours du 9 mars. Pour les exercices suivantes, utilisez les log-rendements mensuels des $N=4$ actions des exercices R du cours 7 : IBM, GM, Hershey Foods et Alcoa.
Utilisez l'index S&P 500 pour le marché et le CPI (consumer price index) pour rendre réels les rendements au besoin.
Le (nouveau) fichier CAPM.zip contient toutes les données nécessaires : regardez la description à la prochaine diapo.
    a. Effectuer le test $J_0$ de la version Sharpe-Lintner du CAPM.
Utilisez le rendement de l'obligation de trésor d'un an comme le rendement $R_f$ sans risque.
    a. Effectuer le test $J_4$ de la version Black du CAPM. Une condition raisonnable de convergence est que le changement fractionnaire de $\hat{\gamma}^*$ est $10^{-6}$.
Vous devriez utiliser une boucle `while` en R. Il y a beaucoup de ressources sur internet pour apprendre comment programmer des boucles. Par exemple, <https://fr.wikibooks.org/wiki/Programmer_en_R/Programmer_une_boucle>.

Le fichier `CAPM.zip` contient :

|fichier|description|
|-------|-----------|
|`CPI.txt`|indice des prix à la consommation, 1962/01 - 2000/01|
|`tresor.txt`|rendement de l'obligation de trésor, 1962/01 - 1999/12|
|`m-sp6299`|rendement du S&P 500, 1962/01 - 1999/12|
|`m-ibm6299`|rendement de l'action IBM, 1962/01 - 1999/12|
|`m-gm6299`|rendement de l'action GM, 1962/01 - 1999/12|
|`m-hsy6299`|rendement de l'action Hershey Foods, 1962/01 - 1999/12|
|`m-aa6299`|rendement de l'action Alcoa, 1962/01 - 1999/12|
