---
title: "Lectures et exercices"
subtitle: "ECN 6578, Hiver 2021"
author: "William McCausland"
date: "`r Sys.Date()`"
output: pdf_document
urlcolor: blue
---

## Cours 1, le 18 janvier

#### Sujets

1. Notation pour les rendements des actifs et des portfeuilles
1. Fonctions linéaires des variables aléatoires, mélanges des lois.
1. La loi des espérances itérées, avec applications
1. L'inégalité de Jensen, avec applications

#### Exercices théoriques

1. Pour les deux placements décrits à la diapo "Fonctions linéaires vs mélanges, un exemple", calculez la moyenne et la variance du rendement.

1. Étudiez la preuve du théorème de variance totale et prouvez le théorème de covariance totale : pour variables aléatoires $X$, $Y$ et $Z$ telles que les moments suivants existent,
\[
  \mathrm{Cov}[X,Y] = E[\mathrm{Cov}[X,Y|Z]] + \mathrm{Cov}[E[X|Z], E[Y|Z]].
\]

1. Soit $Z$ une variable aléatoire qui prend la valeur 1 avec probabilité 1/2 et la valeur -1 avec probabilité 1/2.
Soit $(X,Y)$ un vecteur aléatoire avec la loi conditionnelle sachant $Z$ suivante: $(X,Y)|Z \sim N((Z, -Z), I)$, où $I$ est la matrice identitaire $2\times 2$.
Trouvez $\mathrm{Cov}[X,Y]$.

1. Trouvez l'aplatissement du mélange suivant de deux lois gaussiennes, chacune avec probabilité 0.5 : $N(0,0.9)$ et $N(0,1.1)$.

#### Exercices avec R

(Travail préliminaire, pas à remettre)

1. Téléchargez R et R Studio.
1. Créez un fichier HTML à partir du gabarit R Markdown.

\pagebreak

## Cours 2, le 25 janvier

#### Sujets

1. Log rendements, rendements multi-période, annualisation
1. Asymmétrie et aplatissement, non-normalité des rendements
1. Stationnarité et covariance-stationnarité
1. Non-corrélation versus indépendence.
1. Autocorrélation
1. Faits empiriques

#### Lectures préparatoire (à faire avant le cours)

Dans le livre de Tsay, 3e édition

1. Dans la section 1.1, "Asset Returns"
    a. Multiperiod simple returns
    a. Continuous compounding
    a. Continuously compounded returns
1. Dans la section 1.2, "Distributional properties of returns"
    a. Moments of a random variable (jusqu'à la fin de la page 9)
1. Dans la section 2.2, "Correlation and Autocorrelation"
    a. Introduction (sans nom)
    a. Autocorrelation

#### Autres lectures

1. L'article de Cont (2001) que j'ai mis sur StudiUM.
1. Tsay, 3e édition :
    a. 1.2.1 (lois statistiques et leurs moments)
    a. 1.2.2 (la loi des rendements)
    a. 1.2.3 (rendements multivariés)
    a. 1.2.5 (propriétés empiriques des rendements)
    a. 2.1 (stationnarité)
    a. 2.2 (corrélation et la fonction d'autocorrélation)
    a. 2.3 (le bruit blanc et les séries temporelles linéaires)

#### Exercices

1. La v.a. $X$ suit une loi qui est un mélange de deux lois gaussiennes, chacune avec probabilité 0.5 : $N(\mu,\sigma^2)$ et $N(-\mu,\sigma^2)$.
Calculez l'aplatissement $K_x$ et $\lim_{\sigma^2 \downarrow 0} K_x$.

1. Trouvez l'asymétrie et l'aplatissement d'un mélange général de deux v.a. gaussiennes.
Le site suivant donne les quatres premiers moments non centraux d'une v.a. $N(\mu,\sigma^2)$ : <https://fr.wikipedia.org/wiki/Loi_normale#Moments>.

1. Le prix d'un actif le 4 janvier est de 14.50 dollars. Le prix de l'actif le 15 fevrier est de 13.15. Quel est le rendement simple annualisé et le log rendement annualisé?

1. On observe un échantillon $X_1,\ldots,X_T$, où $X_t \sim \mathrm{iid}\, N(\mu,\sigma^2)$.
Si on fait les tests 1 et 2 de la diapo "Attention : tests multiples!" quelle est la probabilité d'au moins un rejet, comme fonction de $\alpha$?

#### Exercices avec R

Travail, cours du 25 janvier

1. Téléchargez le fichier des données `d-3m7008.txt` et faites la graphique des rendements journaliers de l'action 3M avec la commande `plot`, option 'l' (L minuscule).
1. Faites un test de l'hypothèse que les rendements sont iid gaussiens, avec la statistique test Jarque-Bera. Calculez les valeurs critiques en utilisant la fonction de quantile (comme `qnorm` ou `qchisq`) de la loi asymptotique de la statistique test sous l'hypothèse nulle.
1. Faites un test de l'hypothèse que les rendements sont iid avec variance finie, avec la statistique test Box-Pierce. Utilisez la commande `acf` pour obtenir la fonction d'autocorrélation et calculez la statistique test à partir de cette fonction. Utilisez $m=10$ retards. Confirmez ensuite votre réponse en utilisant la commande `Box.test`.

\pagebreak

## Cours 3, le 1 février

#### Sujets

1. Le bruit blanc et des séries temporelles linéaires
1. Le modèle AR(p)
1. Le modèle MA(p)
1. Le modèle ARMA(p,q)

#### Lectures préparatoire

1. Tsay, 3e édition :
    a. 2.3
    a. 2.4 Intro (avant 2.4.1)
    a. 2.5 Intro (avant 2.5.1)
    a. 2.6 Intro (avant 2.6.1)

#### Autres lectures

1. Tsay, 3e édition :
    a. 2.4 (modèles AR)
    a. 2.5 (modèles MA)
    a. 2.6 (modèles ARMA)
    a. 2.8.1 et 2.8.2 (pour faire l'exercise 2.4)

#### Exercices

1. Ecrivez les équations Yule-Walker pour un process AR(3) et pour un processus ARMA(1,1).

1. Trouvez la fonction d'autocorrélation pour un processus MA(3).

1. Considérez le process AR(3) suivant :
\[
  r_t = 1.9 r_{t-1} - 1.4 r_{t-2} + 0.45 r_{t-3} + a_t.
\]
    a. Il y a une racine réelle du polynôme caractéristique du processus : $0.9^{-1}$.
    Trouvez les autres racines.
    a. Est-ce que la condition de stationnarité tient?

1. Trouvez $\psi_1,\psi_2,\psi_3$ de la représentation MA infinie pour un ARMA(1,2) général.

#### Exercices avec R

Travail, cours du 1 février

1. Considérez le process ARMA(3,1) suivant :
\[
  r_t = 1.9 r_{t-1} - 1.4 r_{t-2} + 0.45 r_{t-3} + a_t - 0.3 a_{t-1}.
\]
    a. Simulez le séries pour $T=500$ observations.
    a. Faites la graphique de la fonction d'autocorrélation $\rho_k$ de la population, pour $k=1,\ldots,25$
    a. Faites la graphique de la fonction d'autocorrélation $\hat\rho_k$ de l'échantillon, pour $k=1,\ldots,25$.
    a. Estimez les paramètres d'un modèle ARMA(3,1) en vous servant de l'échantillon que vous avez tiré. Donnez des estimations ponctuelles avec leurs écarts-types.

1. Tsay, Exercice 2.4. Lisez les sections 2.8.1 et 2.8.2 sur la saisonnalité.

\pagebreak

## Cours 4, le 8 février

#### Sujets

1. Prévision avec un modèle ARMA(p,q)
1. Modèles pour la moyenne conditionnelle, modèles pour la variance conditionnelle.
1. Modèles ARCH et GARCH
    a. propriétés théorique, moments
    a. simulation
    a. évaluation de la log-vraisemblance

#### Lectures préparatoires

1. Tsay, 3e édition
    a. 3.1
    a. 3.2

#### Autres lectures

1. Tsay 3e édition :
    a. Sections 1.2.2 (Distributions des rendements)
    a. Sections 1.2.4 (Fonction de vraisemblance des rendements)
    a. Section 3.3 (Construction des modèles)
    a. Section 3.4.1 (Propriétés des modèles ARCH)
    a. Section 3.4.2 (Faiblesses des modèles ARCH)

#### Exercices

1. Mettons que $r_t$ suit un modèle ARMA(1,3) avec moyenne zéro.
Au moment $t$, trouvez les prévisions de $r_{t+1}$ et de $r_{t+2}$ qui minimisent l'erreur moyenne carrée.
Trouvez la variance de l'erreur de prévision dans les deux cas.

1. Mettons que $r_t$ suit un GARCH(1,1) gaussien avec moyenne zéro.
Calculez la variance, l'asymétrie et l’aplatissement de $r_t$. Vous pouvez vérifier la variance et l'aplatissement en comparant vos résultats aux résultats à la page 132 de Tsay.

#### Exercices en R

Travail, cours du 8 février

1.
    a. Prenez le code de la diapo 'Simulation du modèle ARCH(3)' et modifiez-le pour simuler un GARCH(1,1) gaussien à moyenne zéro pendant $T=1000$ périodes.
Utilisez les valeurs des paramètres $\alpha_0 = 0.000084$, $\alpha_1 = 0.1213$, $\beta_1 = 0.8523$.
    a. Calculez la variance, l'asymétrie et l'aplatissement de l'échantillon.
Suggestion : comparez à la variance, à l'asymétrie et l’aplatissement de la population obtenues dans les exercices théoriques.
    a. Faites la graphique de $r_t$ et de $\sigma_t^2$. 

\pagebreak

## Cours 5, le 15 février

#### Sujets

1. La théorie des estimateurs maximum de vraisemblance
1. Évaluation de la vraisemblance des modèles GARCH
1. Modèle EGARCH et l'effet de levier
1. Introduction à l'inférence bayésienne
1. Modèles de volatilité stochastique

#### Lectures préparatoires

1. Dans Tsay, 3e édition :
    a. 3.5 intro (avant 3.5.1) (Modèle GARCH)
    a. 3.8 intro, 3.8.1 (Modèle EGARCH)
    
1. Au site web suivant : https://fr.wikipedia.org/wiki/Maximum_de_vraisemblance
    a. Sections Exemple, Principe, Définitions, Propriétés, Exemples (au moins l'exemple Poisson)

#### Autres lectures

1. Dans Tsay, 3e édition :
    a. 3.5.1 (exemple GARCH)

#### Exercices

1. Trouvez la moyenne et la variance de $\ln \sigma^2_t$ pour un modèle EGARCH(1,1) avec $\theta = 0$ et $\epsilon_t \sim N(0,1)$.

1. Faites des prévision du rendement $r_{T+1}$ pour une modèle AR(1)-GARCH(1,1).
Quelle est la variance conditionnelle des erreurs de prévision? Exprime le résultat en termes des paramètres, de $r_T$ et de $\sigma_T^2$.

#### Exercices avec R

Travail, cours du 15 février

1. Pour cette question, utilisez les données dans le fichier d-3m7008.txt (action 3M, rendements journaliers, 1970-2008).
Je recommande le paquet fGARCH, utilisé pour les démonstrations du cours 5.
Pour tous les modèles suivants, calculez la valeur maximale de la log-vraisemblance.
Quel est le meilleur modèle selon le critère AIC?
Pour ce modèle, reportez les estimations MV (maximum de vraisemblance) des paramètres et leurs écarts-types asymptotiques et faites la graphique de la séquence de volatilités estimées.
    a. GARCH(1,1), distribution conditionnelle gaussienne.
    a. GARCH(1,1), distribution conditionnelle $t$ de Student.
    a. ARCH(2), distribution conditionnelle $t$ de Student.
    a. GARCH(2,1), distribution conditionnelle $t$ de Student.
    a. AR(1)-GARCH(1,1), distribution conditionnelle $t$ de Student.

\pagebreak

## Cours 6, le 8 mars

#### Sujets

1. Un modèle de volatilité stochastique
1. L'analyse bayésienne
1. La computation bayésienne

#### Lectures préparatoires

1. Dans Tsay, 3e édition :
    a. 3.12 (Modèle de volatilité stochastique)
    a. 12.3 intro, 12.3.1 (inférence bayésienne, lois postérieures)

#### Autres lectures

1. Dans Tsay, 3e édition :
    a. 12.3.2 (lois *a priori* conjuguées)
    a. 12.4.1, 12.4.2 Algorithme Metropolis-Hastings

#### Exercices

1. Trouvez la loi *a posteriori* quand les observations sont iid $\mathrm{Poisson}(\lambda)$ et la loi *a priori* de $\lambda$ est la loi $\mathrm{Gamma(\bar\alpha, \bar\beta)}$, où $\bar\alpha$ et $\bar\beta$ sont des hyperparamètres fixes.

1. Trouvez la loi *a posteriori* conditionnelle de $h$ dans le modèle gaussien.

1. Prenez le modèle de volatilité stochastique avec $\mu=0$. L'exercice est de trouver comment construire la densité prédictive $f(r_{T+1}|r_1,\ldots,r_T)$ sur une grille de points.
    a. Montrez que
\[
  f(r_{T+1}|r_1,\ldots,r_T) = E[f(r_{T+1}|\log h_{T+1}, \log h_T, \theta, r_1,\ldots,r_T)],
\]
où l'espérance est par rapport à la loi conditionnelle de $(\theta,h_T,h_{T+1})$ sachant $r_1,\ldots,r_T$.
    a. Écrivez la densité $f(r_{T+1}|\log h_{T+1}, \log h_T, \theta, r_1,\ldots,r_T)$ en utilisant l'équation d'observation.
    a. Comment peut-on approximer la densité prédictive $f(r_{T+1}|r_1,\ldots,r_T)$ sur une grille à partir d'un échantillon de la loi de $\theta,\log h_T|r_1,\ldots,r_T$? Indice: comme étape intermédiaire, créez un échantillon de la loi de $\theta,\log h_T,\log h_{T+1}|r_1,\ldots,r_T$.

#### Exercices avec R

1. Considérez le modèle de volatilité stochastique décrit dans le cours, avec $\mu=0$.
Regardez aussi la question théorique 3 ci-haut.
Dans le fichier postsim.txt se trouve un échantillon MCMC qui représente la loi *a posteriori* des paramètres $\alpha_0$, $\alpha_1$ et $\omega_v \equiv 1/\sigma_v^2$, ainsi que la log-volatilité $x_T \equiv \log h_T$.
L'échantillon des données utilisé pour l'analyse comprend 3139 log rendments du taux d'échange entre le dollar canadien et l'euro, du 3 janvier 2000 au 4 avril 2012.
Faites la graphique de la densité prédictive de $r_{T+1}$ sur une grille de points dans l'intervalle $[-0.01, 0.01]$.

\pagebreak

## Cours 7, le 15 mars

#### Sujets

1. Des modèles à facteurs
1. Le modèle CAPM
1. Le modèle APT
1. Un modèle à trois facteurs

#### Lectures préliminaires

1. CLM 5.0, 5.1

#### Autres lectures

1. CLM 5.2, 5.3
1. CLM 5.7.1 (anomalies)
1. CLM 6.0, 6.1 (APT)
1. Fama et French (1993), "Common risk factors in the returns on stocks and bonds", *Journal of Financial Economics*. Focalisez sur les Sections 1, 2, 3, 4, 7.

#### Exercices

1. Prouvez les 5 résultats des diapos 16 et 17, « Résultats I » et « Résultats II »

Voici des suggestions pour les 5 résultats :

1. Le résultat dépend de l'unicité de la solution $g + \mu_p h$.
Si vous n'en servez pas, la solution est incorrecte.
1. Exprimez $\sigma_p^2 \equiv (g + \mu_ph) \Omega (g + \mu_ph)$ et minimisez. Écrivez le résultat en terms de $\mu$, $\Omega$.
1. La covariance entre le rendement du portefeuille
$g + \mu_p h$ et celui du portefeuille $g + \mu_q h$ est
$(g+\mu_ph)\Omega(g+\mu_qh)$.
1. Servez-vous du troisième résultat pour trouver le $\mu_{op}$ unique, en termes de $\mu_p$, qui donne $\mathrm{Cov}[R_p,R_{op}] = 0$.
1. La covariance entre le rendement du portefeuille $p$ sur le FMV et le portefeuille arbitraire $\omega$ est
$(g+\mu_ph)\Omega\omega$.
Écrivez-la en forme $\lambda \mu_i + \gamma$, où $\mu_i = E[R_i]$, et $\lambda$ et $\gamma$ sont des fonctions de $\mu_p, A, B, C, D$.
Écrivez l'équation pour deux cas spéciaux, $i=op$ et $i=p$, pour obtenir (5.2.19) dans le manuel CLM.

\pagebreak

## Cours 8, 9, le 22 et le 29 mars

#### Sujets

1. Les facteurs d'actualisation stochastiques
1. Le modèle CCAPM avec utilité isoélastique
1. Les casse-têtes empiriques
1. Utilité Epstein-Zin, utilité isoélastique
1. GMM (Méthode des Moments Généralisée)

#### Lectures préliminaires, Cours 8

1. CLM 8 intro, 8.1 avant 8.1.1.
Ceux qui n'ont jamais vu l'optimisation intertemporel en macroéconomie devraient lire la courte section sur le modèle de Fisher ici :
https://fr.wikipedia.org/wiki/Choix_intertemporel
Le modèle de la première partie de 8.1 est une extension avec un nombre infini de périodes et avec l'incertitude.
C'est plus important de comprendre les détails du modèle discret, page 295-6.

#### Autres Lectures

1. CLM 8.1 (FAS)
1. CLM 8.2 (CCAPM, utilité isoélastiques, casse-têtes empiriques)
1. CLM 8.4 Utilité Epstein-Zin, utilité non-séparable
1. CLM A.2 GMM

#### Exercices, Cours 8

1. Considérez le milieu introduit à la diapo "Absence d'arbitrage et le FAS". Il y a $S=2$ états et 2 actifs. Le premier actif a un rendement net $R_f$ dans les deux états et coûte 100 $. Le deuxième actif a un rendement net $R_1$ dans le permier état et un rendement net $R_2$ dans le deuxième et coûte 500 $.
    a. Donnez les matrices $X$ et $G$ et le vecteur $q$ en termes de $R_f$, $R_1$ et $R_2$.
    a. Donnez une condition nécessaire et suffisante sur $R_f$, $R_1$ et $R_2$ pour la complétion du marché.
    a. Supposant que le marché est complet, trouvez le vecteur des prix d'états et donnez une condition supplémentaire sur $R_f$, $R_1$ et $R_2$ pour l’absence d'arbitrage.
    a. Si les états sont équiprobable ($\pi_1 = \pi_2 = 0.5$) trouvez le facteur d'actualisation stochastique.

2. Considérez le problème à la diapo "Un problème à deux périodes sans incertitude".
    a. Démontrez que si $(C_t^{(i)}, C_{t+1}^{(i)})$ est une solution du problème pour un consommateur avec revenu $m_i$, $i=1,2$, que $(C_t^{(1)}+C_t^{(2)}, C_{t+1}^{(1)}+C_{t+1}^{(2)})$ est une solution du problème pour un consommateur avec revenu $m_1 + m_2$. 
    a. Généralisez le problème à trois périodes. Le taux d'intérêt $R$ est constant et la pondération de $U(C_{t+2})$ est $\delta^2$. Démontrez que pour la solution $(C_t, C_{t+1}, C_{t+2})$, les ratios $C_{t+2}/C_t$ et $C_{t+1}/C_t$ ne dépendent pas du revenu $m$.

#### Exercices, Cours 9

1. Regardez l'expression pour $r_{f,t+1}$ dans le modèle CCAPM avec préférences Epstein-Zin. Pourquoi est-ce la moyenne historique de $r_{f,t+1}$ est plus cohérente avec ce modèle, par rapport au modèle avec préférences isoélastique, quand $\gamma$ est très élevé?
1. Regardez l'expression pour la prime de risque associée à l'actif $i$ dans le même modèle. Quelle est la prime de risque associée au marché (ou portefeuille agrégé)? Pourquoi est-ce que les préférences E-Z aident à capturer la prime historique des actions, par rapport aux préférences isoélastique?
1. Supposons qu'on utilise la méthode GMM pour estimer les paramètres $\delta$ et $\gamma$ du modèle CCAPM avec utilité isoélastique.
On observe $w_t = (C_t, C_{t+1}, R_{t+1}, Z_t)$, $t=1,\ldots,T$.
    a. Pourquoi est-ce qu'on ne devrait pas utiliser, comme élément de $Z_t$, une variable qui n'est pas observée à $t+1$?
    a. Mettons que $Z_t$ comprend une variable observée à $t$ mais qui n'aide pas à prévoir la consommation future $C_{t+1}$. Quelles sont les implications pour l'inférence GMM?
1. Si la fonction de moment $g(w_t,\theta)$ (un vecteur) a un élément qui est une fonction de $w_t$ mais pas de $\theta$, quelles sont les implications pour l'estimation est les tests.

\pagebreak

## Cours 10, le 12 avril

#### Sujets

1. Valeur à risque (VaR, value at risk)
1. Régression quantile

#### Lectures préliminaires

1. CLM chapitre 7 intro, 7.1

#### Autres Lectures

1. CLM 7.2 Riskmetrics
1. CLM 7.3 Approche économétrique à la valeur à risque
1. CLM 7.4 Régression quantile

#### Exercices

1. Supposez que les rendements journaliers d'un actif suivent un modèle GARCH(1,1) gaussien avec $\alpha_0 = 4.2 \times 10^{-6}$, $\alpha_1 = 0.12$, $\beta = 0.85$.
Selons les données $(r_1,\ldots,r_n)$ observées, $\sigma_n = 0.012$ et $r_n = -0.007$. Quelle est la valeur à risque pendant une période d'un jour d'un montant de cet actif qui vaut 10000 dollars à $t=n$?
