---
title: "ECN 7060, Cours 2"
author: "William McCausland"
date: "`r Sys.Date()`"
output: beamer_presentation
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

## Plan de route, Chapitre 2

* 2.1 Définition d'un espace de probabilité
* 2.2 Construction de $(\Omega, {\cal F}, P)$ pour $\Omega$ dénombrable,
      une spécification suffisante (un semi-algèbre ${\cal J}$ et un
      $P\colon{\cal J}\to [0,1])$ avec superadditivité plus monotonicité
      dénombrable) pour $\Omega = [0,1]$
* 2.3 Théorème d'extension: outil pour construire ${\cal F}$, $P$
* 2.4 Application du théorème pour $\Omega = [0,1]$.
* 2.5 Variations du théorème (conditions alternatives)
* 2.6 Application du théorème pour d'autres $\Omega$

## Théorème d'extension

Conditions sur $\Omega$, ${\cal J}$ et $P \colon {\cal J} \to [0,1]$ :

1. ${\cal J}$ est une semi-algèbre sur $\Omega$.
1. $P$ est finiement superadditive.
1. $P$ est dénombrablement monotone.

Conclusion : il y a une tribu ${\cal M}$ sur $\Omega$ et une probabilité $P^*$ sur ${\cal M}$ telles que

1. ${\cal J} \subseteq {\cal M}$,
1. $P^*(A) = P(A)$ pour chaque $A \in {\cal J}$.


## Deux tribus pour $\Omega = \mathbb{R}$ (Exercise 2.4.5)

* ${\cal J}$ est une semi-algèbre si
    * $\emptyset \in {\cal J}$, $\Omega \in {\cal J}$,
    * ${\cal J}$ est stable pour les intersections finies,
    * Si $A \in {\cal J}$, $A^c$ est une réunion disjointe finie des éléments de ${\cal J}$.
* Un intervalle de $\mathbb{R}$ est n'importe $[a,b]$, $[a,b)$, $(a,b]$ ou $(a,b)$, où $a=\infty$, $b=\infty$, $a=b$ (auquel cas $[a,b] = \{a\}$) et $a<b$ (auquel cas $(a,b) = \emptyset$) sont permis.
* Soit ${\cal A}_2 = \{ \mbox{tous intervalles dans}\; \mathbb{R} \}$.
    * Un semi-algèbre?
    * ${\cal B} \equiv \sigma({\cal A}_2)$, la tribu la plus petite qui contient ${\cal A}_2$.
    * Il ne suffit pas de mettre les réunions dénombrables dans ${\cal F}$.
    * Spécification de $P\colon {\cal A}_2 \to [0,1]$?
* Soit ${\cal A}_1 = \{ (-\infty, x] \colon x \in \mathbb{R} \}$.
    * Un semi-algèbre?
    * Pourquoi utile?
* Montrez que $\sigma({\cal A}_1) = {\cal B}$.

## Démonstration de $\sigma({\cal A}_1) = {\cal B} \equiv \sigma({\cal A}_2)$

* ${\cal A}_1 \subset {\cal A}_2$ alors $\sigma({\cal A}_1) \subseteq \sigma({\cal A}_2)$.

* L'autre direction, $\sigma({\cal A}_2) \subseteq \sigma({\cal A}_1)$ :
    * $(a,b] = (-\infty, b] \cap (-\infty, a]^c$ doit être un élément de $\sigma({\cal A}_1)$.
    * $(a,b) = (\cup_n (-\infty, b-1/n]) \cap (-\infty, a]^c \in \sigma({\cal A}_1)$.
    * $[a,b] = (-\infty, b] \cap (\cup_n (-\infty, a-1/n]^c) \in \sigma({\cal A}_1)$.
    * $[a,b) = (\cup_n (-\infty, b-1/n]) \cap (\cup_n (-\infty, a-1/n]^c) \in \sigma({\cal A}_1)$.

* Alors $\sigma({\cal A}_1) = {\cal B} \equiv \sigma({\cal A}_2)$.

## Un semi-algèbre pour $\Omega = \{(r_1,r_2,\ldots): r_i \in \{0,1\}\}$

* $\Omega$ est l'ensemble de séquences infinie des 'piles ou faces'.
* $A_{a_1a_2\ldots a_n} \equiv \{(r_1,r_2,\ldots) \in \Omega \colon r_i = a_i, 1 \leq i \leq n\} \subseteq \Omega$.
* $A_{a_1a_2\ldots a_n}$ est l'ensembles de séquences infinies avec l'histoire initial $a_1a_2\ldots a_n$.
* ${\cal J} \equiv \{A_{a_1a_2\ldots a_n} \colon n\in \mathbb{N}, a_1,\ldots,a_n \in \{0,1\} \}
\cup \{\emptyset, \Omega\}$.
* $A_{a_1a_2\ldots a_n}$ comme un interval de $[0,1)$.
* $A_{01011} \cap A_{0110000} = ?$, $A_{01} \cap A_{01101} = ?$, $A_{a_1a_2\ldots a_n} \cap A_{b_1b_2\ldots b_{n'}} = ?$
* $A_{010}^c = ?$, $A_{a_1a_2\ldots a_n}^c = ?$
* ${\cal J}$ est-il un semi-algèbre?

## Une proto-probabilité pour $\Omega = \{(r_1,r_2,\ldots): r_i \in \{0,1\}\}$

Une 'proto-probabilité' $P \colon {\cal J} \cup \{\emptyset, \Omega\} \to [0,1]$:
$$P(A_{a_1a_2\ldots a_n}) = 1/2^n,\quad P(\emptyset) = 0,\quad P(\Omega) = 1.$$

* Soit $D_1,\ldots,D_n \in {\cal J}$ tel que $D \equiv \cup_{i=1}^n D_i \in {\cal J}$.

* Vérification d'additivité fini de $P \colon {\cal J} \to \mathbb{R}$.

* Il y a un $k \in \mathrm{N}$ tel que $D=A_{a_1a_2\ldots a_k}$ et $P(D) = 2^{-k}$.

* $P(A_{a_1a_2\ldots a_n}) = 2^{-n} = P(A_{a_1a_2\ldots a_n0}) + P(A_{a_1a_2\ldots a_n1}) = 2 \cdot 2^{-n-1}$

* Traversez l'arborescence de bas en haut.

* Pourquoi le cas d'additivité dénombrable n'est pas trivial?

## Un semialgèbre pour $\Omega_1 \times \Omega_2$

* Commençons avec deux espaces de probabilité : $(\Omega_1,{\cal F}_1,P_1)$ et $(\Omega_2,{\cal F}_2,P_2)$.

* Nous voulons construire un semi-algèbre pour $\Omega = \Omega_1 \times \Omega_2$.

* Soit ${\cal J} \equiv \{A \times B \colon A \in {\cal F}_1, B \in {\cal F}_2 \}$.

* $\emptyset, \Omega \in {\cal J}$?

* $(A_1 \times B_1) \cap (A_2 \times B_2) = ?$

* $(A \times B)^c = ?$

## Une proto-probabilité pour ${\cal J} = \Omega_1 \times \Omega_2$

Une 'proto-probabilité' $P \colon {\cal J} \to [0,1]$ :
$P(A \times B) \equiv P_1(A) P_2(B)$.

Vérification d'additivité *finie* (dénombrable plus tard) :

* Si $\cup_{i=1}^n (A_i \times B_i) \in {\cal J}$ alors il existe $\{\alpha_i \colon j \in J\} \subseteq {\cal F}_1$ et $\{\beta_k \colon k \in K\} \subseteq {\cal F}_2$ tels que
    $$\cup_{i=1}^n (A_i \times B_i) = (\cup_{j \in J} \alpha_i) \times (\cup_{k \in K} \beta_i) \equiv A \times B.$$

* $P(A \times B) = P_1(A) P_2(B) = \left(\sum_{j\in J} P_1(\alpha_j) \right)\left(\sum_{k\in K} P_2(\beta_j) \right)$,
$$ \begin{aligned} \sum_{i=1}^n P(A_i \times B_i) &= \sum_{j\in J} \sum_{k\in K} P(\alpha_j \times \beta_k) \\ &= \sum_{j\in J} \sum_{k\in K} P_1(\alpha_j) P_2(\beta_k) \\ &= \left(\sum_{j \in J} P_1(\alpha_j) \right) \left(\sum_{k \in K} P_2(\beta_k) \right) = P(A \times B). \end{aligned} $$
    
## Aperçu du Chapitre 3, partie I

* Définition d'une variable aléatoire :
$X \colon \Omega \to \mathbb{R}$ telle que $\{X \leq x\} \in {\cal F}$ pour chaque $x \in \mathbb{R}$.

* Ce qu'on peut construire sans s'inquiéter si elle est une variable aléatoire ou non:
    * Les indicateurs $1_A(\omega)$, où $A \in {\cal F}$.
    * La somme de deux variables aléatoires, les multiples scalaires des variables aléatoires
    * Les limites des variables aléatoires
    ($Z(\omega) = \lim_{n \to \infty} Z_n(\omega)$ pour $\omega \in \Omega)$)

* Indépendence
    * d'événements (du même espace de probabilité)
    * de collections d'évènements
    * de variables aléatoires

## Aperçu du Chapitre 3, partie II

Convergence monotone d'événements :

* Pour $A_n \equiv [0, 1/n]$, $A_n \searrow \cap_n [0, 1/n] = \{0\}$.
* Pour $A_n \equiv [0, 1-1/n]$, $A_n \nearrow \cup_n [0, 1-1/n] = [0,1)$.

Par convergence de probabilités (un théorème),

* $\lim_{n\to \infty} P([0,1/n]) = P(\{0\})$,
* $\lim_{n\to \infty} P([0,1-1/n]) = P([0,1))$,

## Aperçu du Chapitre 3, partie III

Pour les séquences réels,

* $\liminf_{n \to \infty} x_n \equiv \lim_{n \to \infty} (\inf_{m \geq n} x_m)$
* $\limsup_{n \to \infty} x_n \equiv \lim_{n \to \infty} (\sup_{m \geq n} x_m)$

Exemple : $A_n \equiv (-1)^n (1+1/n) = 2, -3/2, 4/3, -5/3, \ldots$

Pour les suites d'événements, pas forcément monotone,

* $\liminf_{n \to \infty} A_n = \cup_{n=1}^\infty \cap_{k=n}^\infty A_k$
* $\limsup_{n \to \infty} A_n = \cap_{n=1}^\infty \cup_{k=n}^\infty A_k$

Exemple : $H_n \equiv \{(r_1,r_2,\ldots) \in \Omega \colon r_n = 1\}$.
$\liminf_n H_n$ ($H_n$ presque toujours) et $\limsup_n H_n$ ($H_n$ infiniment souvent).
