---
title: "ECN 7060, Cours 7"
author: "William McCausland"
date: "`r Sys.Date()`"
output: beamer_presentation
---

## La fonction caractérisitique

* Comme $F$, une autre représentation complète de la loi d'une v.a.
* Applications :
    * Calcul des moments : moins convenable que la fonction génératrice des moments, mais elle existe toujours
    * L'opération de convolution versus l'opération de multiplication.
    * Théorème central limite
    
## Fonction caractéristique d'une loi $U(a,b)$

$$ \phi(t) = E[e^{itX}] = E[\cos tX + i \sin tX] = \frac{1}{b-a} \int_a^b \cos tx + i \sin tx \, dx $$
$$ \phi(t) = \frac{1}{t(b-a)} \left[ \sin tx - i \cos tx \right]_a^b 
= \frac{1}{it(b-a)} \left[ \cos tx + i \sin tx \right]_a^b $$
$$ \phi(t) = \frac{e^{itb} - e^{ita}}{it(b-a)} $$

* Cas spécial $a = -\theta$, $b = \theta$ :
$$ \phi(t) = \frac{\sin \omega t}{\omega t}. $$
* Cas spécial, $a=-1$, $b=1$ :
$$ \phi(t) = \frac{\sin t}{t} \equiv \mathsf{sinc}(t). $$

## Cas discret

1. $X = x$
\[
  \phi_X(t) = E[e^{itx}] = e^{itx}.
\]
1. $X \sim \mathrm{Bin}(p)$
\[
  \phi_X(t) = (1-p) + pe^{it}.
\]
1. Binomial avec valeurs artitraires
\[
  X = \begin{cases}
  x_0 & \mbox{avec probabilité}\, (1-p), \\
  x_1 & \mbox{avec probabilité}\, p. \\
  \end{cases}
\]
\[
  \phi_X(t) = E[e^{itX}] = (1-p) e^{itx_0} + p e^{itx_1}.
\]
1. Cas spécial $p=1/2$, $x_0 = -\omega$, $x_1 = \omega$
\[
  \phi_X(t) = (e^{-i\omega t} + e^{i\omega t})/2 = \cos \omega t.
\]
1. $X \sim \mathrm{Po}(\lambda)$
\[
  \phi_X(t) = \exp[\lambda(e^{it}-1)].
\]

## Fonction caractéristique d'une loi $N(0,1)$

* Puisque $\sin(tx)$ est impair, $e^{-x^2/2}$ est pair,
$$ \phi(t) = \frac{1}{\sqrt{2\pi}} \int_{-\infty}^\infty \cos tx \cdot e^{-x^2/2}\, dx $$
$$ \phi'(t) = \frac{1}{\sqrt{2\pi}} \int_{-\infty}^\infty -\sin tx \cdot x e^{-x^2/2}\, dx $$

* Intégration par parties, $u = -\sin tx$, $dv = xe^{-x^2/2}\,dx$, $du = -t\cos tx$, $v = -e^{-x^2/2}$, donne
$$ \phi'(t) = [uv]_{-\infty}^\infty - \frac{1}{\sqrt{2\pi}} \int_{-\infty}^\infty t \cos tx \cdot e^{-x^2/2} \, dx = -t \phi(t). $$

* La solution de l'équation différentielle $\log \phi(0) = 0$,
$\frac{d\log \phi(t)}{dt} = -t$
est $\log \phi(t) = \int_0^t -s\, ds = -t^2/2$.

* Alors $\phi(t) = e^{-t^2/2}$.

## Fonction caractérisitique d'une loi $N(\mu,\sigma^2)$

Si $X \sim N(0,1)$ et $Y=\mu + \sigma X$ alors $Y \sim N(\mu, \sigma^2)$ et
\[
  \phi_Y(t) = E[e^{i(\mu + \sigma X)t}] = e^{i\mu t} E[e^{i(t\sigma)X}]
  = e^{i\mu t} \phi_X(\sigma t) = e^{i\mu t} e^{-\sigma^2 t^2/2}
\]

La densité de $Y$ est de la même forme fonctionelle :
\[
  f_Y(y) = \frac{1}{\sqrt{2\pi \sigma^2}}
  \exp\left[-\frac{1}{2} \frac{(x-\mu)^2}{\sigma^2}\right].
\]

## Continuité de la fonction caractéristique

$$ \left| \phi_x(t+h) - \phi_x(t) \right| = \left| \int (e^{i(t+h)x} - e^{itx}) \mu(dx) \right| \leq \int \left| e^{i(t+h)x} - e^{itx} \right| \mu(dx).$$

* Deux bornes qui ne dépend pas de $t$
$$ \left| e^{i(t+h)x} - e^{itx} \right| \leq h|x|, \qquad \left| e^{i(t+h)x} - e^{itx} \right| \leq 2. $$

* Selon la deuxième, (convergence dominée)
$$ \lim_{h \downarrow 0} E\left[\left| e^{i(t+h)X} - e^{itX} \right|\right]
= E\left[\lim_{h \downarrow 0} \left| e^{i(t+h)X} - e^{itX} \right|\right] $$

* Selon la première,
$$ E\left[\lim_{h \downarrow 0} \left| e^{i(t+h)X} - e^{itX} \right|\right] \to 0. $$

## Dérivée de la fonction caractéristique

* Soit $X$ une variables aléatoire, $\phi(t)$ sa fonction caractéristique.
* Si $E[|X|^k] < \infty$, alors pour $0 \leq j \leq k$, $\phi^{(j)}(t) = E[(iX)^j e^{itX}]$.
* Preuve :
    * $E[(iX)^0 e^{itX}] = E[e^{itX}] = \phi(t) = \phi^{(0)}(t)$, alors vrai pour $j=0$.
    * Supposez que $\phi^{(j-1)}(t) = E[(iX)^{j-1} e^{itX}]$.
    * $|(iX)^j e^{itX}| = |i|^j|X|^j|e^{itX}| = |X|^j$
    * $E[|X|^k] < \infty \Rightarrow E[|X|^j] < \infty$
    * $\phi^{(j)}(t) = E\left[ \frac{d}{dt} (iX)^{j-1} e^{itX} \right] = E[(iX)^j e^{itX}]$
* Génération des moments :
$$ \phi^{(j)}(0) = i^j E[X^j] $$

## La fonction $(\sin \theta t) / t = \theta \mathsf{sinc}(\theta t)$

1. Pour $\theta = 0$, $(\sin \theta t) / t \equiv 0$.
1. Pour $\theta \neq 0$, $t=k\pi/\theta$, $k = \pm 1, \pm 2, \ldots$,
$$ \frac{\sin \theta t}{t} = 0. $$
1. Pour $\theta \neq 0$,
$$ \lim_{t \to 0} \frac{\sin \theta t}{t}
= \frac{\lim_{t \to 0} \theta \cos \theta t}{\lim_{t \to 0} 1} = \theta $$
$$ \lim_{t\to \infty} \frac{\sin \theta t}{t} = 0. $$
1. Pour $\theta \neq 0$, la fonction est paire :
$$ \frac{\sin \theta (-t)}{-t} = \frac{\sin \theta t}{t} $$
1. Lemme 11.1.3 du livre,
$$ \lim_{T\to \infty} \int_{-T}^T \frac{\sin \theta t}{t} \, dt
= \begin{cases} \pi & \theta > 0 \\ 0 & \theta = 0 \\ -\pi & \theta < 0 \end{cases} $$

## Théroème d'inversion I

* Soit $\mu$ une mesure borélienne, $\phi(t)$ sa fonction caractéristique. Alors
si $a<b$ et $\mu(\{a\}) = \mu(\{b\}) = 0$,
$$ \mu([a,b]) = \frac{1}{2\pi} \lim_{T\to \infty} \int_{-T}^T \frac{e^{-ita}-e^{-itb}}{it} \phi(t)\,dt $$
* Puisque
$$ \left|\frac{e^{-ita}-e^{-itb}}{it}\right| = \left|\int_a^b e^{itr}\, dr\right| < \infty $$
l'intégral entre $-T$ et $T$ est fini.

* Par Fubini,
$$ \int_{-T}^T \frac{e^{-ita}-e^{-itb}}{it} \int_{\mathbb{R}} e^{itx} \, \mu(dx) \,dt = \int_{\mathbb{R}} \int_{-T}^T
\frac{e^{it(x-a)} - e^{it(x-b)}}{it} \, dt \, \mu(dx). $$

## Théorème d'inversion II

La partie imaginaire de l'intégrand est impair, l'intégral est réel,
$$ \lim_{T\to \infty} \int_{-T}^T \frac{e^{-ita}-e^{-itb}}{it}
\phi(t)\,dt = \int_{\mathbb{R}} \int_{-\infty}^\infty
\frac{\sin t(x-a)}{t} - \frac{\sin t(x-b)}{t} \,dt \, \mu(dx). $$
$$ \frac{1}{2\pi} \lim_{T\to \infty} \int_{-T}^T \frac{e^{-ita}-e^{-itb}}{it}
\phi(t)\,dt = \frac{1}{2} \int_{\mathbb{R}} \mathsf{sign}(x-a) - \mathsf{sign} (x-b) \,\mu(dx). $$

* La valeur de l'intégral est
$$ \frac{1}{2} (\mu(\{a\}) + \mu(\{b\}) + \mu((a,b)). $$

## La dualité en cas de $\phi_X(t)$ intégrable

Théorème d'inversion spécial quand $\phi_X(t)$ est intégrable :

$X$ a une densité
\[
  f_X(x) = \frac{1}{2\pi} \int_{\mathbb{R}} e^{-itx} \phi_X(t) dt.
\]

## Unicité de la fonction caractéristique

* Théorème d'unicité ${\cal L}(X) = {\cal L}(Y) \Leftrightarrow \phi_X(t) = \phi_Y(t)$

* $\Rightarrow$ de la définition de la fonction caractéristique en termes de $\mu$

* $\Leftarrow$ du théorème d'inversion.

## Théorème de continuité

* Soit $\mu,\mu_1,\mu_2,\ldots$ des mesures boréliennes, $\phi,\phi_1,\phi_2,\ldots,$ leurs fonctions caractéristiques. Alors $\mu_n$ converge en loi à $\mu$ ssi $\phi_n(t) \to \phi(t)$, $t\in \mathbb{R}$.

* Par la définition de convergence en loi et la continuité des fonctions $\cos xt$ et $\sin xt$ en $x$ pour $t$ donné, si $\mu_n$ converge en loi à $\mu$, $\phi_n(t) \to \phi(t)$ pour $t\in \mathbb{R}$.

* L'autre direction est plus difficile.

## Théorème centrale limite I

* Supposez que $X_1,X_2,\ldots,$ sont iid, avec moyenne 0, variance 1.

* Soit $Y_n = \sqrt{n} \frac{1}{n} \sum_{k=1}^n X_k$. La fonction caractéristique de $Y_n$ est
$$ \phi_n(t) = \phi_X^n\left(\frac{t}{\sqrt{n}}\right)
= \left[ 1 + \frac{it}{\sqrt{n}} E[X_1] + \frac{1}{2} \left(\frac{it}{\sqrt{n}}\right)^2 E[X_1^2] + o(n^{-1}) \right]^n. $$

* Avec $E[X_1] = 0$, $E[X_1^2] = 1$,
$$ \phi_n(t) = \left(1 - \frac{1}{2}\frac{t^2}{n} + o(n^{-1})\right)^n. $$
$$ \log \phi_n(t) = n\log \left( 1 - \frac{1}{2}\frac{t^2}{n} + o(n^{-1}) \right)
= n \left( -\frac{1}{2} \frac{t^2}{n} + o(n^{-1}) \right) $$
$$ \log \phi_n(t) \to -\frac{t^2}{2} $$
$$ \phi_n(t) \to e^{-t^2/2}. $$

## Théorème centrale limite II

* Si $Y$ est une variable aléatoire $N(0,1)$, sa fonction caractéristique est
$\phi(t) = e^{-t^2/2}$.

* Puisque $\phi_n(t) \to \phi(t)$, ${\cal L}(Y_n) \Rightarrow {\cal L}(Y)$.
