---
title: "Devoirs et Lectures, 2019"
author: "William McCausland"
date: "`r Sys.Date()`"
output: pdf_document
---

## Cours 1, le 4 septembre

### Devoirs, Rosenthal (matière du cours 1)

1. Exercice 1.3.1
2. Exercice 1.3.2
3. Exercice 1.3.3
4. Exercice 1.3.4
5. Exercice 1.3.5

### Lectures, Rosenthal (matière du cours 2)

1. Chapitre 1
2. Chapitre 2

Définitions importantes : espace de probabilité; espace d'état; algèbre; tribu; additivité (finie ou dénombrable); stabilité par complémentation, pour les réunions ou intersections (finies ou dénombrables); semi-algèbre.

### Questions sur les lectures

1. Soit $\Omega = [0,1]$. Soit ${\cal F}$ l'ensemble des parties de $\Omega$ qui sont finis ou de complémentaire fini.
    a. Est-ce que ${\cal F}$ est une algèbre? Appuyez votre réponse.
    a. Est-ce que ${\cal F}$ est une tribu (ou $\sigma$-algèbre)? Appuyez votre réponse.

1. Soit $\Omega = \{1,2,3\}$ et ${\cal F} = 2^\Omega$. Trouvez une mesure de probabilité additive $P\colon {\cal F} \rightarrow [0,1]$ sur $(\Omega,{\cal F})$ telle que $P(\{1,2\}) = 3/4$ et $P(\{2,3\}) = 1/2$.

1. Soit ${\cal J} = \{ \emptyset, \{1\}, \{2\}, \ldots, \{n\}, \{1,\ldots,n\} \}$.
Soit $\Omega = \{1,\ldots,n\}$. Montrez que
    a. ${\cal J}$ est stable pour les intersections finies,
    b. $\emptyset \in {\cal J}$ et $\Omega \in {\cal J}$,
    c. tous les éléments de ${\cal J}$ ont un complément par rapport à $\Omega$ qui égale une réunion disjointe finie des éléments de ${\cal J}$,
    d. ${\cal J}$ est une semi-algèbre de parties de $\Omega$.
    
## Cours 2, le 11 septembre

### Devoirs, Rosenthal (matière du cours 2)

1. Exercice 2.7.4
2. Exercice 2.7.8
3. Exercice 2.7.14
4. Exercice 2.7.20
5. Exercice 2.7.22

### Lectures, Rosenthal (matière du cours 3)

1. Chapitre 3

Définitions importantes : variable aléatoire, $\searrow$, $\nearrow$, $\liminf_n$ et $\limsup_n$ pour une suite d'ensembles $A_n$, indépendance d'événements.


### Questions sur les lectures

1. Trouver $\Lambda_1$ tel que $[-1/n,1/n) \searrow \Lambda_1$.
1. Trouver $\Lambda_2$ tel que $[-1+1/n,1-1/n) \nearrow \Lambda_2$.
1. Soit $\Omega = \{1,2,3,4\}$, $A=\{1,2\}$, $B=\{1,3\}$. Soit $D_n$ la séquence où $D_n = A$ pour $n$ pair et $D_n = B$ pour $n$ impair.
    a. Trouvez l'algèbre (sur $\Omega$) le plus petit qui contient $A$ et $B$.
    a. Trouvez $\limsup_{n\to \infty} D_n = \cap_{n=1}^\infty \cup_{k=n}^\infty D_n$
    et $\liminf_{n\to \infty} D_n = \cup_{n=1}^\infty \cap_{k=n}^\infty D_n$.
    a. Soit $P\colon 2^\Omega \to \mathbb{R}$ telle que $(\Omega,2^\Omega,P)$ est un espace de probabilité. Prouver que si $A$ et $B$ sont indépendants, $A$ et $B^c$ le sont aussi.
1. Soit $\Omega = \{1,2,3\}$, ${\cal F} = \{\emptyset,\{1,2\}, \{3\}, \Omega \}$
    a. Donnez une fonction $X \colon \Omega \to \mathbb{R}$ qui est une variable aléatoire sur $(\Omega,{\cal F})$.
    b. Donnez une fonction $f \colon \Omega \to \mathbb{R}$ qui n'est pas une variable aléatoire sur $(\Omega,{\cal F})$.
    
## Cours 3, le 18 septembre

### Devoirs, Rosenthal (matière du cours 3)

1. Exercice 3.6.2
2. Exercice 3.6.6
3. Exercice 3.6.10
4. Exercice 3.6.12

### Lectures, Rosenthal (matière du cours 4)

1. Chapitre 4

Définitions importantes : espérance, variance d'une variable aléatoire simple,
covariance, corrélation entre deux variables aléatoires simples.

### Questions sur les lectures

1. Soit $(\Omega, {\cal F}, P)$ la mesure de probabilité où $\Omega = \mathbb{N} = \{1,2,\ldots\}$, ${\cal F} = 2^\Omega$ et $P$ est la probabilité où $P(\{\omega\}) = 2^{-\omega}$, $\omega \in \mathbb{N}$.
Soit $X(\omega) = 0$.
Pour $n \in \mathbb{N}$, soit
$$ X_n(\omega) = \begin{cases} 2^n & \omega=n \\ 0 & \omega \neq n. \end{cases}$$
Trouver $E[X]$ et $E[X_n]$. Est-ce que $E[X_n] \to E[X]$?

1. Soit $(\Omega, {\cal F}, P)$ la mesure de probabilité où $\Omega = \mathbb{N} = \{1,2,\ldots\}$, ${\cal F} = 2^\Omega$ et $P$ est la probabilité où $P(\{n\}) = 2^{-n}$, $n \in \mathbb{N}$.
Soit
$$ X(\omega) = \begin{cases} 2, & \omega = 2,3 \\ 1, & \omega = 4 \\ 0, & \mbox{autrement}. \end{cases} $$
Trouver $E[X]$.

1. Soit $(\Omega, {\cal F}, P)$ la mesure de Lebesgue sur $\Omega = [0,1]$. Soit
$$ Y(\omega) = \begin{cases} 1, & \omega\, \mbox{irrationel},\, \omega < 1/2 \\
3, & \omega = 1/2 \\
5, & 1/2 < \omega \leq 1 \\
7, & \mbox{autrement}. \end{cases} $$
Trouver $E[Y]$.

## Cours 4, le 25 septembre

### Devoirs, Rosenthal (matière du cours 4)

1. Exercice 4.5.1
2. Exercice 4.5.2
3. Exercice 4.5.3
4. Exercice 4.5.4
5. Exercice 4.5.13 (considérez les fonctions $\omega^{-1}$, $\omega^{-1/2}$, $(1-\omega)^{-1}$ et $(1-\omega)^{-1/2}$ sur $\Omega$ et leurs combinaisons linéaires).

### Lectures, Rosenthal (matière du cours 5)

1. Chapitres 5, 6

Définitions importantes : convergence presque sur, convergence en probabilité.

### Question sur les lectures

1. Soit $(\Omega, {\cal F}, P)$ un espace de probabilité avec $\Omega = [0,1]$ et $P$, la mesure de Lebesgue.
Pour tous $n>0$, soit $A_n \equiv [0,1/n]$, $Z_n = 1_{A_n}$, $Z=0$.
Lesquelles des affirmations suivantes sont vraies? Expliquez. Pour $Z_n = n1_{A_n}$, est-ce que les réponses changent?
    a. $Z_n \to Z$.
    b. $Z_n$ converge à $Z$ presque surement.
    c. $Z_n$ converge à $Z$ en probabilité.

## Cours 5, le 2 octobre

### Devoirs, Rosenthal (matière du cours 5)

1. Exercice 5.5.2
1. Exercice 5.5.10
1. Exercice 5.5.14
1. Exercice 6.3.2
1. Exercice 6.3.4

### Lectures, Rosenthal (matière du cours 6)

1. Chapitre 9, 10

Définitions importantes : $\liminf$ d'une suite de nombres, $\liminf$ d'une variable aléatoire, fonction géneratrice des moments

### Question sur les lectures

1. Selon le lemme de Fatou, pour une séquence de variables aléatoires $X_n \geq 0$,
$$ E[\liminf_{n\to \infty} X_n] \leq \liminf_{n\to \infty} E[X_n]. $$
Supposez que $(\Omega, {\cal F}, P)$ est un espace de probabilité où
$\Omega = \mathbb{N}$, ${\cal F} = 2^\Omega$ et $P(\{\omega\}) = 2^{-\omega}$.
    a. Montrez que la séquence de variables aléatoires
$X_n = 2^n 1_{\{n\}} (\omega)$ vérifie
$$ E[\liminf_{n\to \infty} X_n] < \liminf_{n\to \infty} E[X_n]. $$
    a. Donnez une séquence de variables aléatoires $X_n \geq 0$ telle que
$$ E[\liminf_{n\to \infty} X_n] = \liminf_{n\to \infty} E[X_n]. $$
    a. Donnez une séquence de variables aléatoires $X_n \geq 0$ telle que
$E[\liminf_{n\to \infty} X_n] < \infty$ et $\liminf_{n\to \infty} E[X_n] = \infty$.
    a. Donnez une séquence de variables aléatoires $X_n \geq 0$ telle que
$E[\liminf_{n\to \infty} X_n] = \infty$ et $\liminf_{n\to \infty} E[X_n] = \infty$.

1. Donnez la fonction génératrice des moments pour une v.a. Bernoulli avec probabilité $p$ de succès.

## Cours 6, le 9 octobre

### Devoirs, Rosenthal (matière du cours 6)

1. Exercice 9.5.4
2. Exercice 9.5.6
3. Exercice 9.5.8
4. Exercice 10.3.4
5. Exercice 10.3.6

### Lectures, Rosenthal (matière du cours 7)

1. Chapitre 11, accent sur l'Intro, 11.1, 11.2
1. (si nécessaire, https://fr.wikipedia.org/wiki/Nombre_complexe)

Définitions importantes : nombres complexes et les operations de base (addition, multiplication, division, exponential, logarithme, magnitude, angle), fonction caractéristique.

### Questions sur les lectures

1. Exprimez les nombres complexes suivants sous la forme $\alpha + i \beta$, où $a,b,c,d,r,\theta\in \mathbb{R}$.
    a. $(a+ib)(c+id)$
    a. $(a+ib)/(c+id)$
    a. $re^{i\theta}$
    a. $\log (a+ib)$

1. Exprimez les nombres complexes suivants sous la forme $re^{i\theta}$, où $a,b,r,r_1,r_2,\theta\in \mathbb{R}$.
    a. $(a+ib)$
    a. $r_1e^{i\theta_1} \cdot r_2e^{i\theta_2}$
    a. $re^{i\theta} \cdot i$
    a. $e^{a+ib}$

1. Les variables aléatoires indépendantes $X_k$, $k=1,2,\ldots$ suivent une loi $\mathrm{Be}(p)$ (Bernoulli) si $P(X_k=0) = (1-p)$ et $P(X_k=1) = p$, $k=1,2,\ldots$.     
    a. Trouvez la fonction caractéristique $\phi_X(t)$ de $X_k$.
    a. La variable aléatoire $Y=\sum_{k=1}^n X_k$ suit une loi $\mathrm{Bi}(n,p)$ (Binomial). Trouvez la fonction caractéristique $\phi_Y(t)$ de $Y$.
    a. Soit $Z=\sqrt{n}(n^{-1}Y-p)$. Trouvez la fonction caractéristique $\phi_Z(t)$ de $Z$.

## Cours 7, le 16 octobre

### Devoirs, Rosenthal (matière du cours 7)

1. Exercice 11.5.7
2. Exercice 11.5.11
3. Exercice 11.5.15 (ajouter la distribution $\mathrm{Ga}(\alpha,\beta)$, utilisez les fonctions caractéristiques et non le « hint »)
4. Exercice 11.5.16
5. Exercice 11.5.18

### Lectures, Rosenthal (matière du cours 8)

1. Chapitre 13 de Rosenthal

### Questions sur les lectures (pas de questionnaire, cours 8)

1. Exercises 13.4.1, 13.4.2, 13.4.5
1. Généralisez le théorème de variance totale (théorème 13.3.1) à un théorème de covariance totale (aléas $X$ et $Y$, sous-tribu ${\cal G}$)

## Cours 8, le 30 octobre

### Devoirs, Rosenthal (matière du cours 8)

1. Exercice 13.4.2
1. Exercice 13.4.6
1. Exercice 13.4.8
1. Exercice 13.4.10
1. Exercice 13.4.12

### Lectures, Casella et Berger (matière du cours 9)

1. Sections 6.1, 7.1
1. Assez de 6.2, 6.3 pour faire les exercices 6.3, 6.6, 6.12(a), 6.14, 6.18
1. Assez de 7.2 pour faire l'exercice 7.9

## Cours 9, le 6 novembre

### Devoirs, Casella et Berger (matière du cours 9)

1. Exercice 6.9 (a,b,c)
1. Exercice 6.11
1. Exercice 6.12
1. Exercice 7.24

### Lectures, Casella et Berger (matière du cours 10)

1. Sections 7.2.3, 7.3
1. Page Wikipédia https://en.wikipedia.org/wiki/Admissible_decision_rule
1. Questions suggérées : 7.19, 7.20, 7.21, 7.22
