---
title: "ECN 7060 Examen Intra 2019"
date: "`r Sys.Date()`"
output: pdf_document
fontsize: 12pt
---

1. Pour $A_n = [-n, (-1)^n/n]$, trouvez $\sup_{k\geq n} A_k$, $\inf_{k \geq n} A_k$, $\limsup_n A_n$ et $\liminf_n A_n$.
Trouvez une représentation simple de l'ensemble $\{x \in \mathbb{R} \colon 1 \in \limsup_n \{e^{2\pi inx}\}\}$.

1. Soit $A_n$ une suite d'événements sur $(\Omega, {\cal F}, P)$.
Montrez que $P(\limsup A_n) \geq \limsup P(A_n)$.
Sur un espace de probabilité $(\Omega, {\cal F}, P)$ de votre choix, donnez un exemple d'une suite $A_n$ où l'inégalité tient avec égalité et un autre exemple où l'inégalité est stricte.

1. Considérez le théorème 10.1.1. Démontrez que la condition (3) implique la condition (1). Vous pouvez utiliser la preuve dans le livre, mais faites-la dans vos propres mots et expliquez les étapes.

1. Soit $(\Omega,{\cal F},P)$ un espace de probabilité où $\Omega = [0,1]$, ${\cal F}$ est borélien et $P$ est la mesure de Lebesgue. Soit $X(\omega) = 1/\omega$.
    a. Trouvez une séquence $X_n(\omega)$ de variables aléatoires simples telles que $X_n \leq X$ et $\lim_{n\to \infty} E[X_n] = \infty$.
    a. Trouvez $E[X]$.
    a. Supposez que $Y \sim N(10^6, 1)$. Soit
    $$ Z = \begin{cases} Y^{-1} & Y \neq 0, \\ 0 & Y = 0. \end{cases}$$
    Qu'est-ce que vous pouvez conclure sur la valeur de $E[Z]$?
    Expliquez brièvement.

1. Si $X \sim N(\mu, \sigma^2)$, trouvez $E[X^3]$. Utilisez la fonction caractéristique.

1. Montrez que la loi $\chi^2(\nu)$ est infiniment divisible. Utilisez la fonction caractéristique.

1. Montrez que la condition $X_n \overset{a.s.}{\to} X$ a.s. dans la proposition 9.1.5. ne peut pas être remplacé par $X_n \overset{p}{\to} X$. (Trouvez un contre-exemple.)

1. Soit $({\cal F}_\alpha)_{\alpha \in A}$ une famille de tribus sur l'ensemble $\Omega$. Montrez que $\cal G = \cap_{\alpha \in A} {\cal F}_\alpha$ est aussi une tribu sur $\Omega$.

1. Si $A_1, A_2, \ldots, A_n$ sont des événements indépendants, montrez que la probabilité pour qu'aucun des $A_i$ ne soit réalisé est au plus égale à $\exp(-\sum_{i=1}^n P(A_i))$.