---
title: "Actions cachées, aléa morale, problèmes principal-agent"
subtitle: "ECN 6013, automne 2019"
author: "William McCausland"
date: "`r Sys.Date()`"
output: beamer_presentation
fig_width: 6
fig_height: 4
urlcolor: blue
---

## Actions cachées, aléa morale, problèmes principal-agent

* Un agent économique a un contrôle partiel sur un résultat (accident ou non, succès ou échec d'un projet).
* Son action (prudence, effort) n'est pas observée (par un assureur, par un employeur).
* Les actions qui augmentent la probabilité d'un bon résultat sont coûteuses pour l'agent.
* L'agent a de l'aversion pour le risque.
* Une réduction de risque atténue les incitations pour choisir les `bonnes' actions.
* Partager le risque avec d'autres personnes entraine une externalité.
* Tension entre la réduction de risque et les bonnes incitations.

## Assurance avec action cachée

Exemples d'aléa morale en assurance

* Comportement au volant et assurance automobile
* Protection du domicile et assurance maison
* (Absence d') assurance pour perte de capital dans la maison.
* Assurance incendie et incendie criminel
* Assurance vie, meurtre et suicide
* Comportement des banques sous l'assurance implicite des gouvernements

Les actions prises ne sont pas efficaces, à cause d'une différence entre les coûts ou bénéfices privés et les coûts ou bénéfices sociaux.

## Les problèmes principal-agent

* Étudiés en droit, économie, sciences politiques.
* Interaction entre un (des) principal et un (des) agent.
* Le principal veut inciter l'agent à faire quelque chose.
* L'agent effectue une action cachée.
* Souvent le principal peut plus facilement tolérer du risque.
* Exemples : (principal, agent)
    * actionnaires, gérant
    * employeur, employé
    * client, mécanicien
    * propriétaires des terrains, agriculteurs
    * électorat, politiciens
    * politiciens des pays riches, bureaucrates de l'aide étrangère
    * système légal, conducteurs, firmes, etc. (degré de prudence)

## Aparté: la fonction d'utilité CARA

* La fonction d'utilité CARA (Constant Absolute Risk Aversion)
\[
	v(x) = \begin{cases}
	  \frac{1}{\lambda} (1-e^{-\lambda x}) & \lambda > 0, \\
	  x & \lambda = 0.
	 \end{cases}
\]
* Elle est monotone et concave:
\[
	v'(x) = \frac{1}{\lambda} (\lambda e^{-\lambda x}) > 0
	\qquad
	v''(x) = -\lambda e^{-\lambda x} < 0
\]
* L'aversion absolue pour le risque (indice Arrow-Pratt) est de
\[
	-\frac{v''(x)}{v'(x)} = \lambda.
\]
* Plus grand $\lambda$, plus de l'aversion; $\lambda = 0$ est la neutralité.

## L'espérance d'utilité CARA pour un risque Gaussien

* Si $x\sim N(\mu, \sigma^2)$, $E[e^x] = e^{\mu + \sigma^2/2}$ et alors
\[
	E[e^{-\lambda x}] = e^{-\lambda \mu + \lambda^2 \sigma^2/2}.
\]
* L'équivalent certain d'un risque Gaussien $x\sim N(\mu,\sigma^2)$, selon l'utilité CARA:
\[
  \begin{aligned}
			E[v(x)] &= E\left[\frac{1}{\lambda}(1-e^{-\lambda x})\right]
			= \frac{1}{\lambda}(1-e^{-\lambda(\mu-\lambda \sigma^2/2)}) \\
			&= v(\mu - \lambda \sigma^2/2).
  \end{aligned}
\]
* La prime de risque ici est de $\lambda \sigma^2/2$ :
    * on accepte $\lambda \sigma^2/2$ moins en espérance pour avoir un montant certain, ou
    * il faut donner une compensation moyenne de $\lambda \sigma^2/2$ pour faire accepter le risque.

## Un premier modèle principal-agent (manuel IEA)

L'agent :

* choisit d'accepter ou rejeter un contrat du principal,
* le cas échéant, choisit un niveau $e\geq 0$ d'effort,
* a une utilité de réservation $u_0$,
* obtient l'utilité $E[v(w - e^2/(2a))]$, où
    * $w$ est le paiement du principal,
    * $v(w)$ est CARA avec aversion $\lambda$ pour le risque,
    * $a>0$ est l'habileté de l'agent, *observée*. (L'effort est plus facile si $a$ est élevé, mais pas plus efficace.)

Un projet du principal :

* La valeur du projet est de $x \sim N(e,\sigma^2)$.

Le principal : (neutre pour le risque)

* offre un contrat à l'agent qui paie $sx + y$ à l'agent,
* maximise la valeur nette (après le paiement) espérée du projet.

## Le problème de l'agent

* Son utilité s'il accepte le contrat est de
\[
	u = E[v(sx + y - e^2/(2a))] = v(se + y - e^2/(2a) - \lambda s^2 \sigma^2/2).
\]
* L'effort optimal ($u$ est une fonction concave d'une fonction concave en $e$ alors concave) :
\[
	\frac{\partial u}{\partial e} = v'(se + y - e^2/(2a) - \lambda s^2 \sigma^2/2)(s - e/a),
	\qquad
	e^* = sa.
\]
* Son utilité indirecte (pour $e=e^*$) :
\[
	\begin{aligned}
		u^*(s,y) &= v(s^2a + y - \lambda s^2 \sigma^2/2 - s^2a^2/(2a)) \\
		&= v(s^2a/2 + y - \lambda s^2 \sigma^2/2).
	\end{aligned}
\]
* Il accept le contrat $(s,y)$ si $u^*(s,y) \geq u_0$, ou si
\[
	v(y + s^2a/2 - \lambda s^2 \sigma^2/2) \geq u_0.
\]

## Le problème du principal

* La condition pour accepter le contrat devient la contrainte de participation pour le principal
\[
	y + s^2a/2 - \lambda s^2 \sigma^2 / 2 \geq v^{-1}(u_0).
\]
* Elle est saturée, alors $y=v^{-1}(u_0) - s^2a/2 + \lambda s^2 \sigma^2/2$.
* La valeur nette du projet est de
\[
	\begin{aligned}
		\pi = E[x-sx-y] &= (1-s)sa - (v^{-1}(u_0) - s^2a/2 + \lambda s^2 \sigma^2/2) \\
		&= sa - s^2a/2 - v^{-1}(u_0) - \lambda s^2 \sigma^2/2.
	\end{aligned}
\]
* La part optimale:
\[
	\frac{\partial \pi}{\partial s} = a - sa - \lambda s \sigma^2,
	\qquad \frac{\partial^2 \pi}{\partial s^2} = -a-\lambda\sigma^2 < 0,
\]
\[
	\qquad s^* = \frac{a}{a+\lambda \sigma^2}.
\]

## Notes sur le problème principal-agent

* Le principal veut donner les bonnes incitations pour l'effort, mais doit compenser l'agent pour assumer du risque.
* L'effort efficace $e=a$ égalise le gain marginal ($v'$) et le coût marginal ($v'\cdot e/a$) d'un agent qui garde tout le profit marginal.
* Si le principal observe l'effort, $e=a$ est optimal (et efficace)
* Si l'agent est neutre pour le risque ($\lambda = 0$), $s=1$ est optimal pour le principal et puis $e=a$ est le choix de l'agent.
* Si $\lambda > 0$, le principal choisit $s<1$ et l'agent $e<a$.
* Interpretations de $s$ :
    * $s=1$ : vente du projet à l'agent pour $-y$.
    * $s=0$ : relation employeur/employée avec salaire versé,
    * $0<s<1$ : commission de vente, métayage, franchisage

## Un modèle principal-agent avec actions discrètes

* L'agent :
    * choisit d'accepter ou de rejeter un contrat du principal,
    * le cas échéant, choisit un niveau $e\in \{0,1\}$ d'effort,
    * a une utilité de réservation $u_0$,
    * obtient l'utilité $E_e[u(s)] - c_e$ sous le contrat s'il fait l'effort $e$, avec $c_1 > c_0 = 0$, $u$ concave.
    * maximise son utilité.

* Un projet du principal :
    * réussit avec probabilité $\pi_e$, selon l'effort $e$ de l'agent, avec $\pi_1 > \pi_0$,
    * vaut 1 au cas de succès, 0 sinon.

* Le principal:
    * est neutre pour le risque,
    * choisit un contrat $(s_0,s_1)$ qui paie $s_1$ en cas de succès, $s_0$ sinon
    * maximise la valeur espérée du projet moins le paiement espéré à l'agent (par neutralité pour le risque)

## Le cas où l'effort est observé

Dans ce cas, le principal peut acheter la participation à bas effort au coût $\sigma_0$ qui vérifie la contrainte de participation $u(\sigma_0) = u_0$, c'est à dire au coût
\[
	\sigma_0 \equiv u^{-1}(u_0).
\]
Ou il peut acheter la participation à haut effort au coût $\sigma_1$ qui vérifie la contraint de participation $u(\sigma_1) - c_1 = u_0$, c'est à dire au coût
\[
	\sigma_1 \equiv u^{-1}(u_0+c_1).
\]

Notes :

* Le profit dans le premier cas est de $\pi_0 - \sigma_0 = \pi_0 - u^{-1}(u_0)$.
* Le profit dans le deuxième cas est de $\pi_1 - u^{-1}(u_0+c_1)$.
* Le principal choisit le contrat (ou $\sigma_0$ pour $e=0$ ou $\sigma_1$ pour $e=1$) qui maximise son profit,
* Le principal assume tout le risque car l'agent est assuré contre le risque. (L'agent est payé pour l'effort et non le résultat.)
* L'allocation est efficace.

## Le cas où l'effort n'est pas observé

La stratégie :

1. trouver le contrat qui incite $e=0$ et qui maximise le profit parmi tous les contrats qui incite $e=0$, (il y a une contrainte de compatibilité des incitations pour éviter $e=1$)
1. trouver le contrat qui incite $e=1$ et qui maximise le profit parmi tous les contrats qui incite $e=1$, (il y a une contrainte de compatibilité des incitations pour éviter $e=0$)
1. choisit le contrat le plus payant entre les deux.

La première étape est facile :

* Considérez le contrat $(s_0, s_1) = (\sigma_0, \sigma_0)$, où $\sigma_0 \equiv u^{-1}(u_0)$.
* On obtient la participation avec $e=0$ pour le salaire constant $\sigma_0$, qui était optimal dans un problème moins contraignant.
* Alors ce contrat doit être optimal parmi les contrats qui incitent $e=0$.

## Étape 2 : contrat optimal parmi ceux qui incitent $e=1$

* Prenons $u(s) = s^\alpha$, $0 < \alpha < 1$ (concave)
* La contrainte de participation est $E_{e=1}[u(s)] - c_1 \geq u_0$ :
\begin{equation}\label{e:part}
	\pi_1 s_1^\alpha + (1-\pi_1) s_0^\alpha - c_1 \geq u_0.
\end{equation}
* La contrainte de compatibilité des incitations est $E_{e=1}[u(s)] - c_1 \geq E_{e=0}[u(s)]$ :
\[
	\pi_1 s_1^\alpha + (1-\pi_1) s_0^\alpha - c_1 \geq \pi_0 s_1^\alpha + (1-\pi_0) s_0^\alpha,
\]
ou
\begin{equation}\label{e:incent}
	s_1^\alpha - s_0^\alpha \geq c_1 / (\pi_1 - \pi_0).
\end{equation}
* Le problème du principal est
\[
	\max_{s_0,s_1} \pi_1 (1-s_1) + (1-\pi_1) (-s_0) \quad \mbox{s.c.} \quad \eqref{e:part}, \eqref{e:incent}
\]
* Remarque : si \eqref{e:part} et \eqref{e:incent} sont saturées, il y a un seul contrat $(s_0,s_1)$ qui vérifie les deux ; ce contrat donne le maximum.

## La contrainte de participation est saturée

* Mettons que non : alors la solution $(s_0, s_1)$ vérifie la contrainte de compatibilité des incitations et
\[
	\pi_1 s_1^\alpha + (1-\pi_1) s_0^\alpha - c_1 = u' > u_0.
\]
* Remplacer $s_1^\alpha$ par $s_1^\alpha - (u'-u_0)$, $s_0^\alpha$ par $s_0^\alpha - (u'-u_0)$ et la contrainte de participation tient toujours.
* La contrainte de compatibilité des incitations tient toujours elle aussi.
* Le profit du principal est plus élevé.
* Contradiction : $(s_0, s_1)$ ne peut pas être la solution.

## La contrainte de compatibilité des incitations est saturée

* Mettons que non: la solution $(s_0, s_1)$ résout le problème avec fonction de Lagrange
\[
  \begin{aligned}
	  L(s_0,s_1,\lambda) &=
		\pi_1 (1-s_1) + (1-\pi_1) (-s_0) \\
		&+ \lambda (\pi_1 s_1^\alpha + (1-\pi_1)s_0^\alpha - c_1 - u_0).
	\end{aligned}
\]
* $L(s_0,s_1,\lambda)$ est concave et un point stationnaire vérifie
\[
	\frac{\partial L}{\partial s_0} = -(1-\pi_1) + \lambda (1-\pi_1) \alpha s_0^{\alpha-1} = 0,
\]
\[
	\frac{\partial L}{\partial s_1} = -\pi_1 + \lambda \pi_1 \alpha s_1^{\alpha-1} = 0.
\]
* On a $\lambda = s_0^{1-\alpha}/\alpha = s_1^{1-\alpha}/\alpha$, alors $s_0 = s_1$.
* Intutition : s'il n'avait pas besoin d'inciter $e=1$, le principal assurerait l'agent complètement.
* $s_0 = s_1$ n'est pas cohérent avec la contrainte de compatibilité des incitations : il y a une contradiction.

## La solution au problème de l'étape 2

* Les deux contraintes sont saturées, alors on obtient $s_0^\alpha$ et $s_1^\alpha$ comme la solution de deux équations linéaires (les deux contraintes, mais avec égalité).
* En général, on obtient le contrat $(s_0,s_1)$ optimal (parmi les contrats qui incitent $e=1$) par $s_0 = u^{-1}(u(s_0))$, $s_1 = u^{-1}(u(s_1))$ ; ici, cela veut dire $s_0 = (s_0^\alpha)^{1/\alpha}$, $s_1 = (s_1^\alpha)^{1/\alpha}$.
* On calcul le profit espéré maximal (parmi les contrats qui incitent $e=1$) comme $\pi_1 - \pi_1 s_1 - (1-\pi_1) s_0$.

## La solution finale

* On compare le profit maximal parmi les contrats qui incite $e=1$ avec le profit maximal parmi les contrats qui incite $e=0$, obtenu à l'étape 1 de la « stratégie ».
* La solution globale est celle qui donne le profit maximal (étape 3 de la stratégie).
* La solution dépend des paramètres $\alpha$, $\pi_0$, $\pi_1$, $u_0$, $c_1$.
