---
title: "Information cachée des vendeurs"
subtitle: "ECN 6013, automne 2019"
author: "William McCausland"
date: "`r Sys.Date()`"
output: beamer_presentation
fig_width: 6
fig_height: 4
urlcolor: blue
---

## Cette section

* Information asymétrique des vendeurs lors des négotiations
    * papier de Samuelson (1984)
    * immeubles, durables usagés, items sur eBay, Kijiji
* Information asymétrique dans les marchés
    * papier d'Akerlof (1970)
    * les vendeurs ou les acheteurs ont de l'information asymétrique

## Négotiation avec asymétrie d'information

* Un objet, un acheteur et un vendeur, neutres au risque.
    * La valeur de l'objet est de $v$ au vendeur, $1.5v$ à l'acheteur.
    * Le vendeur connait $v$, l'information cachée.
    * Pour l'acheteur, $v$ est une variable aléatoire, $v \sim U(0,1)$, avant l'achat potentiel.
* Sa valeur propre espérée de $v$ est de $1/2$, sa valeur espérée de l'objet est de $3/4$.
* Il existe toujours un échange mutuellement bénéfique.
* On a une situation asymétrique d'information cachée où seulement le vendeur connait $v$.

## Un mécanisme

* Un mécanisme possible est une offre à prendre ou à laisser par l'acheteur.
    * L'acheteur fait une offre $b$ pour l'objet.
    * Le vendeur accepte, lui donne l'objet et reçoit $b$ de l'acheteur; ou rejette l'offre.
* La stratégie optimale du vendeur est de vendre lorsque $b \geq v$.
* Quelle est la valeur à l'acheteur d'une offre de $b$?
* C'est la valeur espéree sachant la stratégie du vendeur :
\[
  \int_0^b \left(\frac{3}{2}v - b\right)\, dv = \left. \frac{3}{4} v^2 - bv \right|_0^b = -\frac{1}{4} b^2 < 0.
\]
* Il n'y a pas de vente en équilibre, bien que l'acheteur valorise l'objet toujours plus que le vendeur.
* Les deux perdent à cause de l'information asymétrique.

## Un autre mécanisme I

* Un autre mécanisme possible est une offre à prendre ou à laisser par le vendeur.
    * Le vendeur offre un prix $s$ pour l'objet.
    * L'acheteur accepte, paie $s$ au vendeur et reçoit l'objet; ou rejette l'offre.
* Une vente est profitable à tous les deux si $v < s < (3/2)v$.
* Le vendeur n'offre jamais un prix $s$ moins grand que $v$.
* Si l'acheteur accepte les offres $\bar{s}_1$ et $\bar{s}_2 > \bar{s}_1$, le vendeur ne lui offrirait jamais le prix $\bar{s}_1$; si l'acceptation est profitable quand $v=v_1$, elle est profitable quand $v<v_1$.
* Le vendeur offre un prix $\bar{s}$ jusqu'à la valeur $\bar{v}$ et un prix toujours refusé pour $v > \bar{v}$.

## Un autre mécanisme II

* Si $s>\bar{s}$, l'objet est refusé et il n'y a pas d'échange.
* Sachant que l'objet est offert pour $\bar{s}$, la distribution conditionnelle de $v$ est de $v|(s=\bar{s}) \sim U(0,\bar{v})$.
* La valeur pour l'acheteur s'il accepte une offre de $\bar{s}$ est de
\[
  \int_0^{\bar{v}} \frac{1}{\bar{v}} \left( \frac{3}{2} v - \bar{s} \right) \, dv
  = \frac{1}{\bar{v}} \left[ \frac{3}{4}v^2 - \bar{s} v \right]_0^{\bar{v}}
  = \frac{3}{4} \bar{v} - \bar{s} < 0.
\]
* Encore, il n'y a pas d'échange.

## Le marché pour les auto usagées

* L'exemple précédent: négociation entre deux parties.
* Ici: marché avec qualité cachée, tout se vend au même prix.
* Les éléments essentiels:
    * Les vendeurs observent la qualité de leur auto.
    * Les acheteurs n'observent pas la qualité.
    * Il y a des acheteurs qui valorisent une auto plus que des vendeurs (sinon, l'allocation est efficace et on ne parle pas d'un échec de marché).
    * Le prix ne peut pas dépendre de la qualité, par manque de crédibilité.
    * Ce prix peut être moins grand que la valeur de réservation d'un vendeur, ce qui empêche un échange gagnant-gagnant.
* Solutions:
    * Intermédiaires, réputation, garanties, marques.
    * Inspections, lois (vice caché) qui concernent le marché des immeubles.

## Information asymétrique dans les marchés

Exemples et applications d'Akerlof :

* liquidité des produits durables (voitures usagées)
* le travail des minorités, la demande pour la certification
* la ventes des produits de qualité (et les copies) et les coûts de la malhonnêteté des contrefacteurs :
    * coût direct : mal fait aux clients trichés.
    * coût indirect : fuite des firmes honnêtes.

## Le modèle d'Akerlof

* Un marché où la qualité $x_i$ (d'une voiture $i$) varie
* Seulement le vendeur de $i$ observe $x_i$.
* Les participants observent le prix $p$ et la qualité moyenne $\mu$, deux quantités observées en équilibre.
* Demande: $Q_d = D(p,\mu)$.
* Offre: $S = S(p)$, $\mu = \mu(p)$.
* En équilibre, $D(p,\mu(p)) = S(p)$.

## Plus sur le modèle d'Akerlof

* Deux groupes 1 et 2 avec utilités (von Neumann-Morgenstern)
\[
	U_1 = M + \sum_{i=1}^n x_i, \qquad U_2 = M + 1.5 \sum_{i=1}^n x_i.
\]
* $x_i \sim \mathrm{iid} U(0,2)$.
* $M$ est la consommation réelle (prix de 1).
* $n$ est le nombre de voitures possédées par un groupe.
* Implications de la linéarité des utilités
    * neutralité pour le risque (la qualité moyenne détermine la demande)
    * solutions de coin possibles
    * agrégation
* Dotations:
    * Groupe 1 commence avec $N$ autos; groupe 2 avec 0.
    * Groupe 1 a un revenu $Y_1$; groupe 2, $Y_2$.
    
## La demande et l'offre: information asymétrique

Demande et l'offre du groupe 1:
\[
	D_1(p,\mu) =
	\begin{cases}
		Y_1/p & p < \mu \\
		0 & p > \mu
	\end{cases}
\]
\[
	S_1 =
	\begin{cases}
		pN/2 & p \leq 2 \\
		N & p > 2
	\end{cases}
	\qquad
	\mu =
	\begin{cases}
		p/2 & p\leq 2 \\
	  1 & p>2
	\end{cases}
\]

Demande et l'offre du groupe 2:
\[
	D_2(p,\mu) =
	\begin{cases}
		Y_2/p & p < 1.5\mu \\
		0 & p > 1.5\mu
	\end{cases}
	\qquad
	S_2 = 0
\]

Demande totale:
\[
	D(p,\mu) =
	\begin{cases}
		(Y_1 + Y_2)/p & p < \mu \\
		Y_2/p & \mu < p < 1.5 \mu \\
		0 & p > 1.5 \mu
	\end{cases}
\]

## Équilibre: information asymétrique

* La qualité moyenne est de $\mu = p/2$.
* La demande est nulle pour $p > 1.5\mu$.
* En équilibre, il n'y a pas de vente.

## La demande et l'offre: information symétrique

* Tout le monde ignore la qualité des voitures, $\mu=1$.
* L'offre est
\[
	S(p) = \begin{cases}
		N & p>1 \\
		0 & p<1
	\end{cases}
\]
* La demande est
\[
	D(p) = \begin{cases}
		(Y_1 + Y_2)/p & p<1 \\
		Y_2/p & 1<p<3/2 \\
		0 & p>3/2.
	\end{cases}
\]
* Cas de prix: $p<1$, $p=1$, $1<p<3/2$, $p=3/2$, $p>3/2$.
* Écarter $p<1$ et $p>3/2$ tout de suite.
* Cas $p=3/2$: $S=N$, $D \in [0,2Y_2/3]$. Équilibre si $N \leq 2Y_2/3$.
* Cas $1<p<3/2$: $S=N$, $D = Y_2/p$. Équilibre si $1 < Y_2/N < 3/2$.
* Cas $p=1$: $S\in[0,N]$, $D = Y_2$. Équilibre si $Y_2 \leq N$.

## Les équilibres: information symétrique

Équilibres possibles, selon les valeurs de $N$, $Y_2$ :
\[
	(p,Q) = \begin{cases}
		(1,Y_2) & Y_2 \leq N \\
		(Y_2/N,N) & 2Y_2/3 < N < Y_2 \\
		(3/2,N) & N \leq 2Y_2/3 \\
	\end{cases}
\]

* Dans le premier cas, un surplus de $Y_2/2$ aux acheteurs,
* Dans le deuxième cas, un surplus de $N/2$, partagé,
* Dans le troisième cas, un surplus de $N/2$ aux vendeurs.
